package api

import "net/http"

func (s *Server) collectionsPage(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write([]byte(brandedPage(shelledPage(collectionsHTML))))
}

// collectionsHTML is the Collections page: the basket of shots pinned from
// library search results, one expandable card per collection. Like every
// other page here it is one inline constant with no build step, and the admin
// token lives only in the shell's input element -- never in browser storage.
// The page keeps its own CSS minimal because the shell supplies the chrome;
// mutating actions (reorder, remove, delete) are admin routes, so they fail
// with the API's envelope error when the token input is empty.
const collectionsHTML = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Timingdex · 收藏</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#101827;color:#edf3ff;font:14px ui-sans-serif,system-ui,-apple-system,sans-serif}a{color:#b8c8ff;text-decoration:none}.wrap{max-width:980px;margin:auto;padding:32px 24px 64px}h1{font-size:32px;margin:0 0 6px;letter-spacing:-.04em}.muted{color:#aab8d0;line-height:1.6;margin:0}.collections{display:grid;gap:12px;margin-top:20px}.coll-card{background:#172238;border:1px solid #2c3d5b;border-radius:14px}.coll-head{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:15px 18px;cursor:pointer}.coll-card.open .coll-head{border-bottom:1px solid #2c3d5b}.coll-title{display:grid;gap:3px;min-width:0}.coll-title b{font-size:16px;color:#fff}.coll-desc{color:#93a5c3;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.coll-meta{color:#93a5c3;font-size:12px;white-space:nowrap}.coll-tools{display:flex;justify-content:flex-end;gap:8px;padding:12px 18px 0}.coll-shots{display:grid;gap:10px;padding:14px 18px 18px}.coll-shots[hidden],.player-wrap[hidden]{display:none}button{background:#86a3ff;color:#091227;border:0;border-radius:8px;padding:7px 11px;font-weight:800;cursor:pointer;font:inherit}button.ghost{background:#31446a;color:#dbe6ff}button.danger{background:#7c3a4a;color:#ffd7dd}button.arrow{padding:7px 9px}button:disabled{opacity:.4;cursor:default}.shot-row{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;border:1px solid #2b3e5b;border-radius:10px;padding:11px 13px;background:#121f34}.shot-info{display:grid;gap:3px;min-width:0}.shot-info b{color:#e8efff;font-size:13px;word-break:break-all}.shot-time{color:#93aaff;font-size:12px;font-weight:700}.shot-desc{color:#aab8d0;font-size:12px;line-height:1.5}.chips{display:flex;gap:5px;flex-wrap:wrap;margin-top:2px}.chip{background:#233451;color:#b8c9ff;border-radius:99px;padding:2px 8px;font-size:11px}.shot-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.player-wrap{width:100%}.shot-player{width:100%;border-radius:10px;background:#000}.coll-empty{border:1px dashed #475b7a;border-radius:14px;padding:26px;color:#aab8d0;text-align:center;line-height:1.7}.coll-muted{color:#93a5c3;font-size:12px;padding:4px 2px}.status{border-radius:10px;padding:12px 14px;margin-top:18px;line-height:1.6;display:none}.status.ok{display:block;background:#153c31;color:#a4efc8;border:1px solid #23664f}.status.bad{display:block;background:#3f2230;color:#ffc2cc;border:1px solid #6d3547}
</style></head><body><!--SHELL_HEADER--><main class="wrap">
<h1>收藏</h1>
<p class="muted">在素材库的搜索结果里把值得留下的镜头钉进收藏篮，随时回看或导出时间码。</p>
<div id="collections-status" class="status"></div>
<section id="collections" class="collections"></section>
</main><script>
const shotCache={};
function adminToken(){const el=document.getElementById('admin-token');return el?el.value.trim():''}
function authHeaders(base){const headers=new Headers(base||{});const token=adminToken();if(token)headers.set('Authorization','Bearer '+token);return headers}
async function apiErrMsg(r){try{const d=await r.json();if(d&&d.error&&d.error.message)return d.error.action?(d.error.message+'（'+d.error.action+'）'):d.error.message}catch(_){}return (await r.text()).trim()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function collSay(message,ok){const el=document.getElementById('collections-status');el.className='status '+(ok?'ok':'bad');el.textContent=message}
function fmtClock(ms){const s=Math.max(0,Math.round((ms||0)/1000));const h=Math.floor(s/3600),m=Math.floor(s%3600/60),sec=s%60;const mm=String(m).padStart(2,'0'),ss=String(sec).padStart(2,'0');return h?h+':'+mm+':'+ss:mm+':'+ss}
function fmtDur(ms){const s=Math.max(0,Math.round((ms||0)/1000));const m=Math.floor(s/60),sec=s%60;return m>=60?fmtClock(ms):m+':'+String(sec).padStart(2,'0')}
async function collectionsLoad(){try{const list=await fetch('/api/v1/collections',{headers:authHeaders()}).then(async r=>{if(!r.ok)throw Error(await apiErrMsg(r));return r.json()});collectionsRender(Array.isArray(list)?list:[])}catch(e){document.getElementById('collections').innerHTML='';collSay('无法读取收藏：'+e.message,false)}}
function collectionsRender(list){const el=document.getElementById('collections');if(!list.length){el.innerHTML='<div class="coll-empty">还没有收藏。在素材库的搜索结果里把镜头加入收藏。<br><a href="/">去素材库看看</a>。</div>';return}el.innerHTML=list.map(collectionCard).join('')}
 function collectionCard(c){const count=Number.isFinite(Number(c.shot_count))?Number(c.shot_count):0;return '<div class="coll-card" data-coll="'+esc(c.id)+'"><div class="coll-head" data-action="toggle-collection"><div class="coll-title"><b>'+esc(c.name)+'</b>'+(c.description?'<span class="coll-desc">'+esc(c.description)+'</span>':'')+'</div><span class="coll-meta">'+count+' 个镜头 · 总时长 '+fmtDur(c.total_duration_ms||0)+' · 创建于 '+esc(new Date(c.created_at).toLocaleString('zh-CN'))+'</span></div><div class="coll-tools"><button class="ghost danger" data-action="delete-collection">删除收藏</button></div><div class="coll-shots" data-shots="'+esc(c.id)+'" hidden></div></div>'}
function collectionToggle(id){const box=document.querySelector('[data-shots="'+id+'"]');const card=document.querySelector('[data-coll="'+id+'"]');if(!box||!card)return;if(!box.hidden){box.hidden=true;card.classList.remove('open');return}box.hidden=false;card.classList.add('open');if(box.dataset.loaded)return;box.dataset.loaded='1';shotsLoad(id)}
async function shotsLoad(id){const box=document.querySelector('[data-shots="'+id+'"]');if(!box)return;box.innerHTML='<div class="coll-muted">正在读取镜头…</div>';try{const shots=await fetch('/api/v1/collections/'+encodeURIComponent(id)+'/shots',{headers:authHeaders()}).then(async r=>{if(!r.ok)throw Error(await apiErrMsg(r));return r.json()});shotCache[id]=Array.isArray(shots)?shots:[];shotsRender(id,shotCache[id])}catch(e){box.innerHTML='';collSay('无法读取镜头：'+e.message,false)}}
function shotsRender(id,shots){const box=document.querySelector('[data-shots="'+id+'"]');if(!box)return;if(!shots.length){box.innerHTML='<div class="coll-muted">这个收藏还没有镜头。</div>';return}box.innerHTML=shots.map(function(s,i){return shotRow(id,s,i,shots.length)}).join('')}
function shotRow(cid,s,i,total){const objects=(s.objects||[]).map(function(o){return '<span class="chip">'+esc(o)+'</span>'}).join('');return '<div class="shot-row" data-cid="'+esc(cid)+'" data-shot="'+i+'"><div class="shot-info"><b>'+esc(s.filename||'')+'</b><span class="shot-time">'+fmtClock(s.start_ms)+' – '+fmtClock(s.end_ms)+'</span>'+(s.description?'<span class="shot-desc">'+esc(s.description)+'</span>':'')+(objects?'<span class="chips">'+objects+'</span>':'')+'</div><div class="shot-actions"><button class="ghost arrow" title="上移" data-action="move-shot" data-dir="-1"'+(i===0?' disabled':'')+'>↑</button><button class="ghost arrow" title="下移" data-action="move-shot" data-dir="1"'+(i===total-1?' disabled':'')+'>↓</button><button class="ghost" data-action="play-shot">播放</button><button class="ghost" data-action="copy-timecode">复制时间码</button><button class="ghost danger" data-action="remove-shot">移除</button></div><div class="player-wrap" hidden></div></div>'}
async function shotMove(cid,i,dir){const shots=shotCache[cid];if(!shots||window.collectionReorders[cid])return;const j=i+dir;if(j<0||j>=shots.length)return;window.collectionReorders[cid]=true;const moved=shots.splice(i,1)[0];shots.splice(j,0,moved);const ids=shots.map(function(s){return s.shot_id});try{const response=await fetch('/api/v1/collections/'+encodeURIComponent(cid)+'/shots/reorder',{method:'POST',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify({shot_ids:ids})});if(!response.ok){if(response.status===409){collSay('收藏顺序已被其他操作更新，正在刷新…',false);await shotsLoad(cid);return}throw Error(await apiErrMsg(response))}shotsRender(cid,shots)}catch(e){collSay('调整顺序失败：'+e.message,false);await shotsLoad(cid)}finally{delete window.collectionReorders[cid]}}
async function shotRemove(cid,i){const shot=shotCache[cid]&&shotCache[cid][i];if(!shot)return;try{await fetch('/api/v1/collections/'+encodeURIComponent(cid)+'/shots/'+encodeURIComponent(shot.shot_id),{method:'DELETE',headers:authHeaders()}).then(async r=>{if(!r.ok)throw Error(await apiErrMsg(r))});await shotsLoad(cid);await collectionsLoad()}catch(e){collSay('移除镜头失败：'+e.message,false)}}
async function collectionDelete(id){if(!confirm('删除这个收藏？收藏里的镜头不会从素材库消失。'))return;try{await fetch('/api/v1/collections/'+encodeURIComponent(id),{method:'DELETE',headers:authHeaders()}).then(async r=>{if(!r.ok)throw Error(await apiErrMsg(r))});collSay('收藏已删除。',true);await collectionsLoad()}catch(e){collSay('删除收藏失败：'+e.message,false)}}
function shotPlay(cid,i){const shot=shotCache[cid]&&shotCache[cid][i];if(!shot)return;const row=document.querySelector('[data-shot="'+i+'"][data-cid="'+cid+'"]');if(!row)return;const wrap=row.querySelector('.player-wrap');document.querySelectorAll('.shot-player').forEach(function(v){if(v.closest('.player-wrap')!==wrap)v.pause()});if(!wrap||!wrap.hidden){if(wrap)wrap.hidden=true;return}let video=wrap.querySelector('video');if(!video){video=document.createElement('video');video.className='shot-player';video.controls=true;video.preload='metadata';video.src='/api/v1/assets/'+encodeURIComponent(shot.asset_id)+'/proxy#t='+(shot.start_ms/1000).toFixed(3)+','+(shot.end_ms/1000).toFixed(3);wrap.appendChild(video)}wrap.hidden=false;video.currentTime=shot.start_ms/1000;video.play().catch(function(){})}
async function copyTimecode(cid,i){const shot=shotCache[cid]&&shotCache[cid][i];if(!shot)return;const text=fmtClock(shot.start_ms)+'–'+fmtClock(shot.end_ms);try{await navigator.clipboard.writeText(text);collSay('已复制时间码 '+text,true)}catch(e){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();try{document.execCommand('copy');collSay('已复制时间码 '+text,true)}catch(e2){collSay('复制失败：'+e2.message,false)}ta.remove()}}
window.collectionReorders={};document.getElementById('collections').addEventListener('click',function(e){const target=e.target.closest('[data-action]');if(!target)return;const card=target.closest('[data-coll]'),cid=card&&card.dataset.coll;if(!cid)return;const row=target.closest('[data-shot]'),i=row&&Number(row.dataset.shot);if(target.dataset.action==='toggle-collection')collectionToggle(cid);else if(target.dataset.action==='delete-collection'){e.stopPropagation();collectionDelete(cid)}else if(row&&target.dataset.action==='move-shot')shotMove(cid,i,Number(target.dataset.dir));else if(row&&target.dataset.action==='play-shot')shotPlay(cid,i);else if(row&&target.dataset.action==='copy-timecode')copyTimecode(cid,i);else if(row&&target.dataset.action==='remove-shot')shotRemove(cid,i)});collectionsLoad();
</script></body></html>`
