package api

// progressHTML is the /progress monitor.
const progressHTML = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NexusSlate · [[i18n:progress.title]]</title><style>

.console-hero{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap;padding:16px 18px;margin:var(--s4) 0}
.chain{margin:var(--s4) 0}
.hero-title{display:grid;gap:4px}
.hero-job{font-size:19px;font-weight:850;color:var(--text)}
.hero-meta{font-size:12px}
.panels{display:grid;grid-template-columns:1.4fr .8fr;gap:16px}
.panels>*{min-width:0}
.panel>h2{padding:var(--s4) var(--s5) 0;margin:0 0 var(--s4)}
.panel>#jobs{padding:0 var(--s5) var(--s5)}
details.panel summary{padding:var(--s4) var(--s5);cursor:pointer;font-family:var(--font-ui);font-size:var(--fs-title);font-weight:700;list-style:none}
details.panel summary::-webkit-details-marker{display:none}
details.panel summary:hover{background:var(--raised)}
details.panel[open] summary{border-bottom:1px solid var(--rule)}
details.panel>.log{padding:var(--s5)}
details.panel>#supervisor{padding:var(--s5);min-width:0}
.log{font-family:var(--font-data);font-size:12px;line-height:1.55;color:var(--text-muted);min-height:280px;max-height:480px;overflow:auto;white-space:pre-wrap}
.log div{padding:6px 0;border-bottom:1px solid var(--graticule)}
.callout .issue-head{flex:1 1 100%;font-weight:700}
.callout .issue-row{flex:1 1 100%;display:flex;align-items:center;gap:var(--s3);flex-wrap:wrap;border-top:1px solid var(--rule);margin-top:var(--s3);padding-top:var(--s3)}
.callout .issue-label{font-weight:600}
.callout .issue-counts{color:var(--text-muted);font-family:var(--font-data)}
.callout .issue-actions{margin-left:auto;display:flex;gap:var(--s2);flex-wrap:wrap}
@media(max-width:760px){.panels{grid-template-columns:1fr}}

</style></head><body><!--SHELL_HEADER--><main class="wrap"><header class="pagehead"><h1>[[i18n:progress.title]]</h1><p class="muted">[[i18n:progress.pollNote]]</p></header><section id="issues" hidden></section><div class="console-hero" data-console-hero aria-live="polite"><div class="hero-title"><span class="muted">[[i18n:status.processing]]</span><div class="hero-job" id="hero-job">[[i18n:progress.hero.idle]]</div><div class="hero-meta muted" id="hero-meta"></div></div><div class="hero-actions"><button id="run" class="primary" onclick="runPipeline()">[[i18n:progress.run]]</button><button id="resume" onclick="resumeDeferred()" hidden>[[i18n:progress.resume]]</button><button id="retry" onclick="retryFailed()" hidden>[[i18n:progress.retryFailed]]</button></div></div><section id="pipeline-chain" class="chain" aria-label="[[i18n:progress.chain.label]]"><div class="chain-step" data-stage="probe"><span class="k">probe</span><span class="v">[[i18n:progress.chainStage.probe]]</span></div><div class="chain-step" data-stage="derive"><span class="k">derive</span><span class="v">[[i18n:progress.chainStage.derive]]</span></div><div class="chain-step" data-stage="speech_gate"><span class="k">speech_gate</span><span class="v">[[i18n:progress.chainStage.speech_gate]]</span></div><div class="chain-step" data-stage="transcribe"><span class="k">transcribe</span><span class="v">[[i18n:progress.chainStage.transcribe]]</span></div><div class="chain-step" data-stage="analyze"><span class="k">analyze</span><span class="v">[[i18n:progress.chainStage.analyze]]</span></div><div class="chain-step" data-stage="index"><span class="k">index</span><span class="v">[[i18n:progress.chainStage.index]]</span></div></section><section id="metrics" class="metrics"></section><section class="panels"><div class="panel"><h2>[[i18n:progress.jobs.title]]</h2><div id="jobs" class="muted">[[i18n:progress.loading]]</div></div><details class="panel" id="log-panel"><summary>[[i18n:progress.log.title]]</summary><div id="log" class="log"></div></details></section><details class="panel" id="supervisor-panel"><summary>[[i18n:progress.supervisor.label]]</summary><div id="supervisor" class="muted">[[i18n:progress.supervisor.loading]]</div></details></main><script>
 function csrfToken(){const prefix='__Host-nexusslate_csrf=';const item=document.cookie.split('; ').find(function(x){return x.indexOf(prefix)===0});return item?decodeURIComponent(item.slice(prefix.length)):''}
 function authHeaders(base){const headers=new Headers(base||{});const csrf=csrfToken();if(csrf)headers.set('X-CSRF-Token',csrf);return headers}
const logEl=document.getElementById('log');let logs=[];function log(m){logs.unshift(tdFormatTime(new Date())+'  '+esc(m));logs=logs.slice(0,30);logEl.innerHTML=logs.map(x=>'<div>'+x+'</div>').join('')}function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function when(v){const t=new Date(v);return isNaN(t.getTime())?String(v||''):tdFormatDateTime(t)}
function tdJobState(s){return s==='pending'?tdT('status.queued'):s==='running'?tdT('status.processing'):s==='succeeded'?tdT('progress.state.succeeded'):s==='failed'?tdT('status.failed'):s==='skipped'?tdT('progress.state.skipped'):s}
function stateCell(j){if(j.deferred_reason)return '<span class="state deferred">'+esc(tdT('status.deferred'))+'</span>';const st=tdJobState(j.state);return '<span class="state '+esc(j.state)+'">'+esc(j.terminal?st+tdT('progress.state.terminalSuffix'):st)+'</span>'}
function detailCell(j){if(j.deferred_reason)return esc(tdT('progress.deferredDetail',{time:when(j.run_after)}));return esc(j.last_error||(j.has_error?tdT('progress.detail.hasError',{detail:tdT('progress.adminDetails')}):'')||when(j.run_after)||'—')}
// The metric row is counted by the database, not tallied from the rows below
// it. Those rows are the newest hundred jobs, which during a scan are all
// freshly enqueued work -- tallying them reported a library with thousands of
// finished jobs as "0 done" and left it there.
function renderMetrics(s){const rows=[['progress.metric.pending',s.pending],['status.processing',s.running],['progress.metric.failed',s.failed]];document.getElementById('metrics').innerHTML=rows.map(m=>'<div class="metric"><span class="k">'+esc(tdT(m[0]))+'</span><span class="v">'+(m[1]||0)+'</span></div>').join('')}
function renderActions(s){const run=document.getElementById('run'),resume=document.getElementById('resume'),retry=document.getElementById('retry');run.hidden=s.failed>0||s.deferred>0;resume.hidden=!(s.failed<=0&&s.deferred>0);retry.hidden=!(s.failed>0)}
function highlightChain(jobType){const cells=document.querySelectorAll('#pipeline-chain .chain-step');cells.forEach(function(c){c.classList.remove('is-active')});if(!jobType)return;const cell=document.querySelector('#pipeline-chain [data-stage="'+esc(jobType)+'"]');if(cell)cell.classList.add('is-active')}function renderHero(jobs){const el=document.getElementById('hero-job'),meta=document.getElementById('hero-meta');if(!el||!meta)return;const running=jobs.find(j=>j.state==='running')||jobs.find(j=>j.state==='pending');if(!running){el.textContent=tdT('progress.hero.idle');meta.textContent=jobs.length?tdPlural('progress.hero.queue',jobs.length):tdT('progress.hero.queueEmpty');highlightChain('');return}const jobTypeKeys={probe:'progress.jobType.probe',derive:'progress.jobType.derive',speech_gate:'progress.jobType.speech_gate',transcribe:'progress.jobType.transcribe',align:'progress.jobType.align',analyze:'progress.jobType.analyze',index:'progress.jobType.index',normalize:'progress.jobType.normalize'};const label=tdT(jobTypeKeys[running.job_type]||running.job_type);el.textContent=(running.filename||running.asset_id||tdT('progress.hero.assetFallback'))+' · '+label;meta.textContent=tdT('progress.hero.attempts',{count:running.attempt_count+'/'+running.max_attempts})+(running.deferred_reason?' · '+tdT('status.deferred'):'');highlightChain(running.job_type)}function render(jobs){document.getElementById('jobs').innerHTML=jobs.length?'<div class="table-scroll"><table class="table"><tr><th>'+esc(tdT('progress.jobs.type'))+'</th><th>'+esc(tdT('progress.jobs.state'))+'</th><th>'+esc(tdT('progress.jobs.attempts'))+'</th><th>'+esc(tdT('progress.jobs.detail'))+'</th></tr>'+jobs.map(j=>'<tr><td>'+esc(j.job_type)+'</td><td>'+stateCell(j)+'</td><td>'+j.attempt_count+'/'+j.max_attempts+'</td><td>'+detailCell(j)+'</td></tr>').join('')+'</table></div>':tdT('progress.jobs.emptyPrefix')+'<a href="/library-roots">'+esc(tdT('shell.nav.mediaFolders'))+'</a>'+tdT('progress.jobs.emptySuffix')}async function refresh(){try{const jobs=await fetch('/api/v1/jobs?limit=100',{headers:authHeaders()}).then(async r=>{if(!r.ok)throw Error(await tdApiErrorMessage(r));return r.json()});render(jobs);renderHero(jobs)}catch(e){document.getElementById('jobs').textContent=tdT('progress.jobs.loadError',{message:e.message})}try{const s=await fetch('/api/v1/jobs/summary',{headers:authHeaders()}).then(async r=>{if(!r.ok)throw Error(await tdApiErrorMessage(r));return r.json()});renderMetrics(s);renderActions(s)}catch(e){log(tdT('progress.metrics.loadError',{message:e.message}))}refreshSupervisor()}
function supervisorText(d){const label=esc(tdT('progress.supervisor.label'));if(!d.enabled)return label+'<b>'+esc(tdT('progress.supervisor.notEnabled'))+'</b>'+esc(tdT('progress.supervisor.disabledDetail'));if(!d.running)return label+'<b>'+esc(tdT('progress.supervisor.notRunning'))+'</b>'+esc(tdT('progress.supervisor.notRunningDetail'));const parts=[label+'<b>'+esc(tdT('progress.supervisor.running'))+'</b>',esc(tdPlural('progress.supervisor.interval',Math.round(d.interval_seconds/60)))];parts.push(d.last_pass_at?esc(tdT('progress.supervisor.lastPass',{time:when(d.last_pass_at)})):esc(tdT('progress.supervisor.notScannedYet')));parts.push(d.scanning?esc(tdT('progress.supervisor.scanning')):(d.next_pass_at?esc(tdT('progress.supervisor.nextPass',{time:when(d.next_pass_at)})):'—'));if(d.last_outcome==='held_off_peak')parts.push(esc(tdT('progress.supervisor.heldOffPeak',{time:d.held_until?when(d.held_until):tdT('progress.supervisor.peakWindowStart')})));else if(d.last_outcome==='pipeline_busy')parts.push(esc(tdT('progress.supervisor.pipelineBusy')));else if(d.last_outcome==='error')parts.push(esc(tdT('progress.supervisor.lastError',{error:d.last_error||tdT('progress.adminDetails')})));else if(d.last_outcome==='scanned')parts.push(esc(tdT('progress.supervisor.scanned',{roots:d.roots_scanned,discovered:d.discovered})));return parts.join(' · ')}
async function refreshSupervisor(){const el=document.getElementById('supervisor');try{const r=await fetch('/api/v1/pipeline/supervisor',{headers:authHeaders()});if(!r.ok)throw Error(await tdApiErrorMessage(r));el.innerHTML=supervisorText(await r.json())}catch(e){el.textContent=tdT('progress.supervisor.loadError',{message:e.message})}}
const issueLabels={'provider_quota':'progress.issue.provider_quota','provider_auth':'progress.issue.provider_auth','provider_unavailable':'progress.issue.provider_unavailable','provider_route_exhausted':'progress.issue.provider_route_exhausted','media_decode':'progress.issue.media_decode','unsupported_media':'progress.issue.unsupported_media','disk_space_low':'progress.issue.disk_space_low','budget_exhausted':'progress.issue.budget_exhausted','source_missing':'status.missing','worker_offline':'progress.issue.worker_offline','configuration':'progress.issue.configuration','unknown':'progress.issue.unknown'};
// The deferral codes are the categories that recover on their own -- their
// parked jobs wake when run_after passes, the disk frees, or the budget
// period rolls over -- so retrying this group must also release the parked
// half, not just requeue failed rows.
const issueAutoRecover={'provider_route_exhausted':true,'disk_space_low':true,'budget_exhausted':true};
// The repair anchor is a literal category→action map, never a blanket
// /providers link: each category points at the one page that truthfully fixes
// it, and a category no page fixes (media_decode, unsupported_media,
// budget_exhausted, unknown) gets no link at all.
const issueRepairRoutes={'provider_quota':'/providers','provider_auth':'/providers','provider_unavailable':'/providers','provider_route_exhausted':'/providers','configuration':'/providers','disk_space_low':'/settings','source_missing':'/library-roots','worker_offline':'/workers'};
const issueRepairLabels={'provider_quota':'progress.issue.openProviders','provider_auth':'progress.issue.openProviders','provider_unavailable':'progress.issue.openProviders','provider_route_exhausted':'progress.issue.openProviders','configuration':'progress.issue.openProviders','disk_space_low':'progress.issue.openSettings','source_missing':'progress.issue.openMediaFolders','worker_offline':'progress.issue.openWorkers'};
 function issuesRow(i){const label=tdT(issueLabels[i.category]||i.category);const count=Number.isFinite(Number(i.count))?Number(i.count):0;const assets=Number.isFinite(Number(i.asset_count))?Number(i.asset_count):0;const route=issueRepairRoutes[i.category];const repair=route?'<a class="btn" href="'+route+'">'+esc(tdT(issueRepairLabels[i.category]))+'</a>':'';return '<div class="issue-row"><span class="issue-label">'+esc(label)+'</span><span class="issue-counts">'+tdPlural('progress.issue.jobs',count)+' / '+tdPlural('progress.issue.assets',assets)+'</span><span class="issue-actions">'+repair+'<button data-action="retry-issue" data-category="'+esc(i.category)+'">'+esc(tdT('progress.issue.retryGroup'))+'</button></span></div>'}
 document.body.addEventListener('click',function(e){const b=e.target.closest('[data-action="retry-issue"]');if(b)retryIssueGroup(b.dataset.category,b)});
async function issuesRefresh(){const el=document.getElementById('issues');if(!el)return;try{const r=await fetch('/api/v1/issues',{headers:authHeaders()});if(!r.ok)throw Error(await tdApiErrorMessage(r));const issues=await r.json();const total=(issues||[]).reduce((n,i)=>n+(Number(i.count)||0),0);if(!total){el.hidden=true;return}el.hidden=false;el.innerHTML='<div class="callout callout--contradicted"><b class="issue-head">'+esc(tdT('progress.issues.attention',{count:total}))+'</b>'+issues.map(issuesRow).join('')+'</div>'}catch(e){el.hidden=false;el.innerHTML='<div class="callout callout--contradicted">'+esc(tdT('progress.issue.loadError',{message:e.message}))+'</div>'}}
async function retryIssueGroup(category,btn){const label=tdT(issueLabels[category]||category);if(btn)btn.disabled=true;log(tdT('progress.issue.retryRequested',{label}));try{const r=await fetch('/api/v1/pipeline/retry-failed',{method:'POST',headers:authHeaders({'content-type':'application/json'}),body:JSON.stringify({category})});if(!r.ok)throw Error(await tdApiErrorMessage(r));const d=await r.json();let extra='';if(issueAutoRecover[category]){const z=await fetch('/api/v1/pipeline/resume-deferred',{method:'POST',headers:authHeaders({'content-type':'application/json'}),body:JSON.stringify({reason:category})});if(!z.ok)throw Error(await tdApiErrorMessage(z));const zd=await z.json();extra=tdPlural('progress.issue.resumeExtra',zd.resumed)}log(tdPlural('progress.issue.requeued',d.requeued,{label})+extra+tdT('progress.startHint',{run:tdT('progress.run')}))}catch(e){log(tdT('progress.retryFailed.error',{message:e.message}))}finally{if(btn)btn.disabled=false;refresh();issuesRefresh()}}
async function retryFailed(){const b=document.getElementById('retry');b.disabled=true;log(tdT('progress.retryFailedRequested'));try{const r=await fetch('/api/v1/pipeline/retry-failed',{method:'POST',headers:authHeaders()});if(!r.ok)throw Error(await tdApiErrorMessage(r));const d=await r.json();log(tdPlural('progress.retryFailed.requeued',d.requeued)+tdT('progress.startHint',{run:tdT('progress.run')}))}catch(e){log(tdT('progress.retryFailed.error',{message:e.message}))}finally{b.disabled=false;refresh()}}async function resumeDeferred(){const b=document.getElementById('resume');b.disabled=true;log(tdT('progress.resume.requested'));try{const r=await fetch('/api/v1/pipeline/resume-deferred',{method:'POST',headers:authHeaders()});if(!r.ok)throw Error(await tdApiErrorMessage(r));const d=await r.json();log(d.resumed?tdPlural('progress.resume.released',d.resumed)+tdT('progress.startHint',{run:tdT('progress.run')}):tdT('progress.resume.none'))}catch(e){log(tdT('progress.resume.error',{message:e.message}))}finally{b.disabled=false;refresh()}}
async function runPipeline(){const b=document.getElementById('run');b.disabled=true;b.textContent=tdT('progress.run.running');log(tdT('progress.run.requested'));try{const r=await fetch('/api/v1/pipeline/run',{method:'POST',headers:authHeaders()});if(!r.ok)throw Error(await tdApiErrorMessage(r));const d=await r.json().catch(()=>({}));log(d.status==='already_running'?tdT('progress.run.alreadyRunning'):tdT('progress.run.started'))}catch(e){log(tdT('progress.run.error',{message:e.message}))}finally{b.disabled=false;b.textContent=tdT('progress.run');refresh()}}refresh();issuesRefresh();setInterval(refresh,2500);setInterval(issuesRefresh,10000);log(tdT('progress.log.opened'));</script></body></html>`
