package api

// The channel manager is the only place a Provider key is ever entered, so the
// page is written against three boundaries that are easy to lose in an edit:
//
//   - A key exists in the browser only as the live value of a password input.
//     It is never stored (no localStorage/sessionStorage), never placed in a
//     URL or query string, never logged, and never rendered back: the admin
//     API blanks secret_ref and returns no api_key, so a re-render after a
//     successful write cannot echo one. Every key input is cleared on success.
//   - PATCH /api/v1/admin/provider-channels/{id} replaces the whole member set
//     (app.UpdateProviderChannel assigns channel.Members from the patch), and a
//     member is matched to its stored secret by id first, label second. So the
//     add/remove affordances resend *every* surviving member with its id and
//     without api_key — that is what preserves the already-stored keys of the
//     other members. Sending only the new member would drop the rest.
//   - Two members of one channel must not share a label. A new member carrying
//     an existing member's label is matched by that label on the server, which
//     would overwrite the older member's secret before the duplicate member id
//     fails the write. The duplicate check below keeps that input out.
//   - Per-member health joins the status endpoint's MemberStatus to a config
//     member row by id: both sides carry the provider_channel_members row id,
//     so the match is exact. A member the executor filters out (disabled, or
//     no stored secret) simply has no status row and renders no health line.
const providersHTML = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Timingdex · 能力与服务</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:var(--ui-bg);color:var(--ui-text);font:15px ui-sans-serif,system-ui,sans-serif}
header{display:flex;gap:18px;align-items:center;padding:15px 5vw;border-bottom:1px solid var(--ui-border)}.brand{font-weight:850;color:#fff;margin-right:auto}a{color:#b9ccf5;text-decoration:none}
.wrap{max-width:1180px;margin:auto;padding:38px 24px}.eyebrow{font-size:12px;font-weight:800;letter-spacing:.1em;color:#96aeff}h1{font-size:42px;letter-spacing:-.05em;margin:8px 0}.muted{color:#a9b9d5;line-height:1.55}
.auth,.panel,.card{background:var(--ui-surface);border:1px solid var(--ui-border);border-radius:14px}.auth,.panel{padding:18px}.auth{display:flex;gap:10px;align-items:end;margin:22px 0}.field{flex:1}label{display:block;font-size:12px;font-weight:800;color:#cbd8f2;margin:0 0 6px}
input,select{width:100%;background:#091322;border:1px solid var(--ui-border-strong);border-radius:8px;color:#fff;padding:10px;font:inherit}button{border:0;border-radius:8px;padding:10px 13px;background:#8ca6ff;color:#081225;font-weight:850;cursor:pointer}
button.ghost{background:transparent;border:1px solid var(--ui-border-strong);color:#c9d9ff;padding:6px 10px;font-size:12px;font-weight:800}button.danger{background:transparent;border:1px solid #7a4058;color:#ffc0ca;padding:5px 9px;font-size:12px;font-weight:800}
.layout{display:grid;grid-template-columns:1fr 1.4fr;gap:16px}.formgrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.wide{grid-column:1/-1}.cards{display:grid;gap:10px}.card{padding:15px}.cardtop{display:flex;justify-content:space-between;gap:12px;align-items:center}.pill{display:inline-block;border-radius:99px;padding:4px 8px;background:#223855;color:#c9d9ff;font-size:11px}.ok{background:#164936;color:#a2efc6}.bad{background:#552d39;color:#ffc0ca}.member{margin-top:9px;padding-top:9px;border-top:1px solid #29405d;color:#aebfdd;font-size:12px}.memberline{display:flex;gap:10px;align-items:center;justify-content:space-between}.notice{margin-top:18px;border-left:3px solid #8da7ff;padding:12px 14px;background:#172744;color:#cbd8f2}.error{color:#ffadba}.empty{padding:25px;text-align:center;color:#a8b9d4;border:1px dashed #3c5272;border-radius:12px}
.keyhead{display:flex;justify-content:space-between;align-items:center;margin:16px 0 8px}.keyhead b{font-size:12px;font-weight:800;letter-spacing:.1em;color:#96aeff}.cardactions{display:flex;gap:8px;align-items:center}.memberrow{border:1px solid var(--ui-border);border-radius:10px;background:#0e1a2c;padding:12px;margin-bottom:10px}.rowtop{display:flex;justify-content:space-between;align-items:center;margin-bottom:9px}.rowtop b{font-size:12px;color:#cbd8f2}.addkey{margin-top:12px;padding-top:11px;border-top:1px solid #29405d}.addform{margin-top:10px}[hidden]{display:none}.advanced-config{border:1px solid var(--ui-border);border-radius:10px;background:#0e1a2c;margin-top:10px;padding:10px 12px}.advanced-config summary{cursor:pointer;font-size:12px;font-weight:800;color:#cbd8f2;user-select:none}.advanced-config .formgrid{grid-template-columns:1fr 1fr;gap:10px}.provider-health{display:flex;align-items:center;gap:8px;margin:0 0 12px;min-height:16px}.pill.warn{background:#5c4a1e;color:#ffd88a}.member-health{display:flex;align-items:center;gap:8px;margin-top:7px}.member-meta{margin-top:5px;font-size:11px}
.probe-row{display:flex;gap:8px;align-items:center}.probe-row input{flex:1}.probe-row button{white-space:nowrap}
@media(max-width:760px){.layout,.formgrid{grid-template-columns:1fr}.auth{display:block}.auth button{margin-top:10px}.wrap{padding:28px 18px}}
</style></head><body><!--SHELL_HEADER--><main class="wrap"><div class="head"><div><div class="eyebrow">MODEL CHANNELS</div><h1>能力与服务</h1><p class="muted">按能力管理模型通道。同一通道可配多个 Key，运行时按并发最少优先轮换；某个 Key 额度用尽或临时失败时自动降级到同通道其他 Key。</p></div><div class="head-actions"><button type="button" class="primary" id="new-channel-btn">新增通道</button><button type="button" class="ghost" id="quick-config-btn">一键配置</button><button type="button" class="ghost" id="refresh-channels">刷新</button></div></div><div class="auth-callout" id="auth-callout" hidden>需要 Hub 管理 Token 才能查看与配置通道。<button type="button" id="login-prompt">登录以查看</button></div><p class="muted">Token 只保留在当前页面内存，不会写入浏览器存储。API Key 通过管理员 HTTPS 请求写入 Hub 加密密钥库，页面不回显。</p><section class="panel"><div class="cardtop"><h2>已配置通道</h2><span class="pill">Video analysis · ASR · 语义检索 · Tag curation · Repurpose</span></div><p class="provider-health" id="provider-health"></p><p id="channels-status" class="muted"></p><div id="channels" class="empty">加载中…</div></section></main>
<dialog id="provider-dialog" class="ui-dialog"><button type="button" class="ui-dialog__close" data-close="provider-dialog" aria-label="关闭">×</button><h3 id="dialog-title">新增模型通道</h3><form id="channel-form" onsubmit="saveChannel(event)"><div class="formgrid">
<div><label for="capability">能力</label><select id="capability"><option value="video_analysis">Video analysis</option><option value="asr">ASR</option><option value="embedding">语义检索</option><option value="tag_curator">Tag curation</option><option value="repurpose">Repurpose</option></select></div>
<div><label for="provider-name">Provider</label><select id="provider-name"></select></div>
<div><label for="label">通道名称</label><input id="label" required placeholder="例如 Gemini 主账号"></div><div><label for="model">模型</label><div class="probe-row"><input id="model" placeholder="模型 ID" list="model-options"><datalist id="model-options"></datalist><button type="button" class="ghost" id="probe-models" onclick="probeModels()">读取模型</button></div></div>
<div class="wide"><label for="endpoint">Endpoint</label><input id="endpoint" placeholder="https://…"></div>
</div>
<div class="keyhead"><b>KEY 列表</b><button type="button" class="ghost" onclick="addMemberRow()">+ 再加一个 Key</button></div>
<div id="member-rows"><div class="memberrow"><div class="rowtop"><b>默认 Key</b></div><div class="formgrid">
<div><label for="member-label">Key 名称</label><input id="member-label" class="m-label" value="primary" required></div><div><label for="api-key">API Key</label><input id="api-key" class="m-key" type="password" autocomplete="new-password" required></div>
</div><details class="advanced-config wide"><summary>高级配置</summary><div class="formgrid"><div><label for="weight">权重</label><input id="weight" aria-label="权重" class="m-weight" type="number" min="1" value="1"></div><div><label for="max-inflight">并发上限</label><input id="max-inflight" aria-label="并发上限" class="m-inflight" type="number" min="1" value="1"></div></div></details>
</div></div></div>
<button type="submit">保存到 Hub 密钥库</button><p id="form-status" class="muted"></p></form></dialog>
<dialog id="quick-dialog" class="ui-dialog"><button type="button" class="ui-dialog__close" data-close="quick-dialog" aria-label="关闭">×</button><h3 id="quick-dialog-title">一键配置模型</h3><p class="muted">Plan 预设行只填 Key：端点与模型已预置，不用读模型列表。自定义端点：填 Endpoint + Key，点「探测能力」让程序读出可用模型，再勾选它要担当的角色。</p><div class="keyhead"><b>PLAN 预设</b></div><div id="quick-rows"></div><div class="keyhead" style="margin-top:18px"><b>自定义端点</b></div><div class="memberrow" id="custom-row"><div class="formgrid"><div><label>Endpoint</label><input id="custom-endpoint" placeholder="https://…（OpenAI 兼容）"></div><div><label>API Key</label><input id="custom-key" type="password" autocomplete="new-password" placeholder="粘贴 Key"></div></div><div class="memberline" style="margin-top:10px"><span id="custom-probe-status" class="muted">尚未探测</span><button type="button" class="ghost" onclick="customProbe()">探测能力</button></div><div id="custom-roles" class="member muted" style="margin-top:8px"></div></div><button type="button" id="quick-go" onclick="quickSubmit()">开始配置</button><p id="quick-status" class="muted"></p></dialog>
<script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const providerOptions={video_analysis:[['gemini','Gemini'],['qwen_video','千问视频'],['volcengine_video','火山视频'],['local_vlm','本地 VLM']],asr:[['stepfun','StepFun'],['qwen','千问 ASR'],['volcengine_asr','火山 ASR']],embedding:[['openai_embeddings','OpenAI-compatible Embeddings'],['gemini_embed_content','Gemini Embeddings'],['volc_agent_plan_embedding','火山 Agent Plan Embeddings'],['volc_coding_plan_embedding','火山 Coding Plan Embeddings']],tag_curator:[['openai_chat','OpenAI-compatible Chat'],['volc_agent_plan','火山 Agent Plan'],['volc_coding_plan','火山 Coding Plan']],repurpose:[['openai_chat','OpenAI-compatible Chat']]};
// Well-known base URLs so the operator only types the key. These mirror the
// shipped config.example.json defaults; a provider with no entry leaves the
// endpoint blank (generic OpenAI-compatible, local, or account-specific).
const endpointPresets={gemini:'https://generativelanguage.googleapis.com/v1beta',gemini_embed_content:'https://generativelanguage.googleapis.com/v1beta',qwen:'https://dashscope.aliyuncs.com/compatible-mode/v1',qwen_video:'https://dashscope.aliyuncs.com/compatible-mode/v1',volcengine_video:'https://ark.cn-beijing.volces.com/api/v3',volc_agent_plan:'https://ark.cn-beijing.volces.com/api/plan/v3',volc_coding_plan:'https://ark.cn-beijing.volces.com/api/coding/v3',volc_agent_plan_embedding:'https://ark.cn-beijing.volces.com/api/plan/v3',volc_coding_plan_embedding:'https://ark.cn-beijing.volces.com/api/coding/v3',stepfun:'https://api.stepfun.com/step_plan/v1',local_vlm:'http://127.0.0.1:8080/v1'};
// endpointTouched separates an auto-filled preset (safe to replace when the
// provider changes) from an operator-typed endpoint (never clobbered).
let endpointTouched=false;
function applyEndpointPreset(){const provider=document.getElementById('provider-name').value;const el=document.getElementById('endpoint');if(!provider||!el||endpointTouched)return;el.value=endpointPresets[provider]||''}
// probeModels is the one-click model-list read: it sends the still-open form's
// endpoint and key to the Hub, which makes one non-billed GET {endpoint}/models
// and returns the model ids (redacted, never echoed back). The key goes no
// further than the same admin HTTPS direction it already travels on save.
function probeModels(){const status=document.getElementById('form-status');const provider=document.getElementById('provider-name').value;const endpoint=document.getElementById('endpoint').value.trim();const keyField=document.querySelector('#member-rows .memberrow .m-key');const key=keyField?keyField.value.trim():'';if(!endpoint){status.textContent='请先填写 Endpoint。';return}if(!key){status.textContent='请先填写一个 API Key 再读取模型列表。';return}status.textContent='正在读取模型列表…';fetch('/api/v1/admin/provider-channels/probe-models',{method:'POST',headers:adminHeaders(true),body:JSON.stringify({provider_name:provider,endpoint:endpoint,api_key:key})}).then(json).then(function(d){const dl=document.getElementById('model-options');dl.innerHTML=(d.models||[]).map(m=>'<option value="'+esc(m)+'"></option>').join('');const model=document.getElementById('model');if(d&&d.models&&d.models.length){if(!model.value.trim())model.value=d.models[0];status.textContent='✓ 读到 '+d.models.length+' 个模型，可从下拉选择或直接输入。'}else{status.textContent='✗ '+((d&&d.message)||'未读到模型列表')}}).catch(function(e){status.textContent='✗ '+e.message})}
// --- 一键配置：Plan 预设 + 自定义端点 ---
// Plan 行只填 Key：端点与模型已探明并写死，用户不需要读 model list。
// 自定义端点：填 Endpoint + Key，程序探测可用模型，用户勾选该端点担当的角色。
// 两个来源可以并存：Plan 键和自定义端点各自补上缺失的能力（跨 plan 混用）。
const modelPresets={stepfun:'stepaudio-2.5-asr',qwen:'qwen3-asr-flash',gemini:'gemini-2.5-flash',qwen_video:'qwen3.6-flash',volcengine_video:'doubao-1.5-vision-pro-250428',local_vlm:'Qwen3-VL-4B-Instruct',volc_agent_plan:'doubao-seed-2.0-lite',volc_coding_plan:'ark-code-latest',volc_agent_plan_embedding:'doubao-embedding-vision-251215',volc_coding_plan_embedding:'doubao-embedding-vision-251215'};
const capNames={video_analysis:'视频理解',asr:'语音识别 ASR',repurpose:'Repurpose 方案',tag_curator:'Tag 策展',embedding:'语义检索 Embedding'};
const planPresets=[
 {id:'volc_agent_plan',name:'火山 Agent Plan',channels:[
   {cap:'repurpose',provider:'volc_agent_plan',endpoint:'https://ark.cn-beijing.volces.com/api/plan/v3',model:'doubao-seed-2.0-lite'},
   {cap:'tag_curator',provider:'volc_agent_plan',endpoint:'https://ark.cn-beijing.volces.com/api/plan/v3',model:'doubao-seed-2.0-lite'},
   {cap:'embedding',provider:'volc_agent_plan_embedding',endpoint:'https://ark.cn-beijing.volces.com/api/plan/v3',model:'doubao-embedding-vision-251215'},
 ]},
 {id:'volc_coding_plan',name:'火山 Coding Plan',channels:[
   {cap:'repurpose',provider:'volc_coding_plan',endpoint:'https://ark.cn-beijing.volces.com/api/coding/v3',model:'ark-code-latest'},
   {cap:'tag_curator',provider:'volc_coding_plan',endpoint:'https://ark.cn-beijing.volces.com/api/coding/v3',model:'ark-code-latest'},
   {cap:'embedding',provider:'volc_coding_plan_embedding',endpoint:'https://ark.cn-beijing.volces.com/api/coding/v3',model:'doubao-embedding-vision-251215'},
 ]},
 {id:'qwen_token_plan',name:'Qwen Token Plan',channels:[
   {cap:'repurpose',provider:'openai_chat',endpoint:'https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1',model:'qwen3.7-plus'},
   {cap:'tag_curator',provider:'openai_chat',endpoint:'https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1',model:'qwen3.7-plus'},
 ]},
 {id:'asr',name:'语音识别 ASR（StepFun）',channels:[
   {cap:'asr',provider:'stepfun',endpoint:'https://api.stepfun.com/step_plan/v1',model:'stepaudio-2.5-asr'},
 ]},
];
function quickCapConfigured(cap){return (channelCache||[]).some(function(c){return c.capability===cap})}
function quickChannelRowHTML(ch){return '<div class="member muted" style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:6px"><span style="min-width:118px">'+esc(capNames[ch.cap])+'</span><span style="display:flex;align-items:center;gap:6px;flex:1;min-width:180px"><label style="margin:0;white-space:nowrap">模型</label><input class="q-model" data-cap="'+ch.cap+'" value="'+esc(ch.model)+'" placeholder="模型 ID（可自定义）"></span><span style="display:flex;align-items:center;gap:6px;flex:2;min-width:240px"><label style="margin:0;white-space:nowrap">Endpoint</label><input class="q-endpoint" data-cap="'+ch.cap+'" value="'+esc(ch.endpoint)+'"></span></div>'}
function quickPlanRowHTML(plan){return '<div class="memberrow" data-plan="'+plan.id+'"><div class="rowtop"><b>'+esc(plan.name)+'</b><span class="pill" data-status></span></div><div class="formgrid"><div><label>API Key</label><input class="q-key" type="password" autocomplete="new-password" placeholder="粘贴 Key（留空跳过）"></div></div><div class="keyhead" style="margin:10px 0 4px"><b>将配置的能力（模型已预填，可改）</b></div>'+plan.channels.map(quickChannelRowHTML).join('')+'</div>'}
function quickRender(){const container=document.getElementById('quick-rows');container.innerHTML=planPresets.map(quickPlanRowHTML).join('');planPresets.forEach(function(plan){const row=container.querySelector('[data-plan="'+plan.id+'"]');const missing=plan.channels.filter(function(ch){return !quickCapConfigured(ch.cap)});const status=row.querySelector('[data-status]');if(missing.length===0){status.className='pill ok';status.textContent='已配置';row.dataset.configured='1';row.querySelector('.q-key').disabled=true}else if(missing.length<plan.channels.length){status.className='pill warn';status.textContent='部分已配置'}else{status.className='pill bad';status.textContent='未配置'}})}
async function openQuick(){await loadChannels();document.getElementById('quick-dialog-title').textContent='一键配置模型';quickRender();customReset();const d=document.getElementById('quick-dialog');if(d&&typeof d.showModal==='function')d.showModal()}
// 自定义端点：程序探测可用模型，用户勾选角色（不填模型名）。
let customModels=[];let customProbed=false;
const customRoles=[['repurpose','Repurpose 方案'],['tag_curator','Tag 策展'],['embedding','语义检索 Embedding'],['video_analysis','视频理解']];
function customReset(){customModels=[];customProbed=false;const roles=document.getElementById('custom-roles');if(roles)roles.innerHTML='';const st=document.getElementById('custom-probe-status');if(st)st.textContent='尚未探测'}
async function customProbe(){const st=document.getElementById('custom-probe-status');const endpoint=document.getElementById('custom-endpoint').value.trim();const key=document.getElementById('custom-key').value.trim();if(!endpoint){st.textContent='请先填 Endpoint';return}if(!key){st.textContent='请先填 API Key';return}st.textContent='正在探测…';try{const d=await fetch('/api/v1/admin/provider-channels/probe-models',{method:'POST',headers:adminHeaders(true),body:JSON.stringify({provider_name:'openai_chat',endpoint:endpoint,api_key:key})}).then(json);customModels=d.models||[];customProbed=true;const roles=document.getElementById('custom-roles');roles.innerHTML='<div class="muted" style="margin-bottom:6px">可用模型 '+customModels.length+' 个：'+esc(customModels.slice(0,6).join('、'))+(customModels.length>6?'…':'')+'</div>'+customRoles.map(function(r){const disabled=quickCapConfigured(r[0]);return '<div style="display:flex;gap:8px;align-items:center;margin:4px 0;flex-wrap:wrap"><label style="display:flex;gap:8px;align-items:center;min-width:150px"><input type="checkbox" class="q-role" data-cap="'+r[0]+'"'+(disabled?' disabled':'')+'>'+esc(r[1])+(disabled?'（已配置）':'')+'</label><input class="q-role-model" data-cap="'+r[0]+'" value="'+esc(customRoleModel(r[0]))+'" placeholder="模型 ID（可自定义）" style="flex:1;min-width:200px"></div>'}).join('');if(d&&d.status!=='ok'){st.textContent='⚠ '+((d&&d.message)||'未读到模型');return}st.textContent='✓ 读到 '+customModels.length+' 个模型，勾选角色'}catch(e){st.textContent='✗ '+e.message;customProbed=false}}
function customRoleModel(cap){const list=customModels||[];if(!list.length)return '';if(cap==='embedding'){const emb=list.find(function(m){return /embed/i.test(m)});if(emb)return emb}if(cap==='repurpose'||cap==='tag_curator'){const chat=list.find(function(m){return !/image|embed|tts|audio/i.test(m)});if(chat)return chat}return list[0]}
function customRoleProtocol(cap){return cap==='embedding'?'openai_embeddings':(cap==='video_analysis'?'openai_video':'openai_chat')}
async function quickSubmit(){const btn=document.getElementById('quick-go');btn.disabled=true;const status=document.getElementById('quick-status');const created=[];const errors=[];let ok=true;const rows=[...document.querySelectorAll('#quick-rows .memberrow')];for(const row of rows){if(row.dataset.configured)continue;const plan=planPresets.find(function(p){return p.id===row.dataset.plan});const key=row.querySelector('.q-key').value.trim();if(!key)continue;for(const ch of plan.channels){if(quickCapConfigured(ch.cap))continue;const chEndpoint=((row.querySelector('.q-endpoint[data-cap="'+ch.cap+'"]')||{}).value||'').trim();const chModel=((row.querySelector('.q-model[data-cap="'+ch.cap+'"]')||{}).value||'').trim();try{const body={capability:ch.cap,label:plan.name,provider_name:ch.provider,endpoint:chEndpoint||ch.endpoint,model:chModel||ch.model,enabled:true,route_order:0,members:[{label:'primary',api_key:key,enabled:true,weight:1,max_inflight:1}]};await fetch('/api/v1/admin/provider-channels',{method:'POST',headers:adminHeaders(true),body:JSON.stringify(body)}).then(json);created.push(capNames[ch.cap]||ch.cap)}catch(e){errors.push((capNames[ch.cap]||ch.cap)+' '+e.message);ok=false}}}
const cep=document.getElementById('custom-endpoint').value.trim();const cek=document.getElementById('custom-key').value.trim();if(cep&&cek){const checked=[...document.querySelectorAll('#custom-roles .q-role:checked')];if(checked.length&&!customProbed){status.textContent='正在探测自定义端点…';try{const d=await fetch('/api/v1/admin/provider-channels/probe-models',{method:'POST',headers:adminHeaders(true),body:JSON.stringify({provider_name:'openai_chat',endpoint:cep,api_key:cek})}).then(json);customModels=d.models||[];customProbed=true}catch(e){errors.push('自定义端点 '+e.message);ok=false}}for(const cb of checked){const cap=cb.dataset.cap;if(quickCapConfigured(cap))continue;const model=((document.querySelector('#custom-roles .q-role-model[data-cap="'+cap+'"]')||{}).value||'').trim()||customRoleModel(cap);if(!model){errors.push((capNames[cap]||cap)+' 未探测到模型');ok=false;continue}try{const body={capability:cap,label:'自定义端点',provider_name:customRoleProtocol(cap),endpoint:cep,model:model,enabled:true,route_order:0,members:[{label:'primary',api_key:cek,enabled:true,weight:1,max_inflight:1}]};await fetch('/api/v1/admin/provider-channels',{method:'POST',headers:adminHeaders(true),body:JSON.stringify(body)}).then(json);created.push(capNames[cap]||cap)}catch(e){errors.push((capNames[cap]||cap)+' '+e.message);ok=false}}}
document.querySelectorAll('#quick-rows .q-key').forEach(function(k){k.value=''});document.getElementById('custom-key').value='';status.textContent=created.length?('已配置 '+created.length+' 个能力通道'+(errors.length?'；失败：'+errors.join('；'):'')):(errors.length?'未配置：'+errors.join('；'):'没有可配置的（未填 Key / 未勾选角色，或都已配置）');btn.disabled=false;await loadChannels();if(created.length&&!errors.length){closeDialog('quick-dialog')}}
let channelCache=[];let statusCache=[];let channelHealth=new Map();let anyRuntimeData=false;
function syncProviderOptions(){const capability=document.getElementById('capability').value;const select=document.getElementById('provider-name');const prior=select.value;select.innerHTML=(providerOptions[capability]||[]).map(([value,label])=>'<option value="'+value+'">'+label+'</option>').join('');if([...select.options].some(o=>o.value===prior))select.value=prior;applyEndpointPreset()}
 function csrfToken(){const prefix='__Host-timingdex_csrf=';const item=document.cookie.split('; ').find(function(x){return x.indexOf(prefix)===0});return item?decodeURIComponent(item.slice(prefix.length)):''}
 function adminHeaders(json=false){const headers={};const csrf=csrfToken();if(csrf)headers['X-CSRF-Token']=csrf;if(json)headers['Content-Type']='application/json';return headers}
async function apiErrMsg(r){try{const d=await r.json();if(d&&d.error&&d.error.message)return d.error.action?(d.error.message+'（'+d.error.action+'）'):d.error.message}catch(_){}return (await r.text()).trim()}
async function json(r){if(!r.ok)throw Error(await apiErrMsg(r));return r.status===204?null:r.json()}
function duplicateLabel(labels){const seen=new Set();for(const raw of labels){const key=String(raw||'').trim().toLowerCase();if(!key)continue;if(seen.has(key))return raw;seen.add(key)}return ''}
 function keyFields(prefix){return '<div class="formgrid"><div><label>Key 名称</label><input class="'+prefix+'label" aria-label="Key 名称" value="" required></div><div><label>API Key</label><input class="'+prefix+'key" aria-label="API Key" type="password" autocomplete="new-password" required></div></div><details class="advanced-config wide"><summary>高级配置</summary><div class="formgrid"><div><label>权重</label><input class="'+prefix+'weight" aria-label="权重" type="number" min="1" value="1"></div><div><label>并发上限</label><input class="'+prefix+'inflight" aria-label="并发上限" type="number" min="1" value="1"></div></div></details>'}
function addMemberRow(){const rows=document.getElementById('member-rows');const row=document.createElement('div');row.className='memberrow';row.innerHTML='<div class="rowtop"><b>追加 Key</b><button type="button" class="danger rowremove">移除这一行</button></div>'+keyFields('m-');rows.appendChild(row);const label=row.querySelector('.m-label');label.value='key-'+rows.children.length;row.querySelector('.rowremove').addEventListener('click',()=>row.remove());label.focus()}
function formMembers(){return [...document.querySelectorAll('#member-rows .memberrow')].map(row=>({label:row.querySelector('.m-label').value.trim(),api_key:row.querySelector('.m-key').value.trim(),enabled:true,weight:Number(row.querySelector('.m-weight').value)||1,max_inflight:Number(row.querySelector('.m-inflight').value)||1}))}
function clearFormKeys(){document.querySelectorAll('#member-rows .m-key').forEach(input=>{input.value=''});[...document.querySelectorAll('#member-rows .memberrow')].slice(1).forEach(row=>row.remove())}
function memberPatches(channel){return (channel.members||[]).map(m=>({id:m.id,label:m.label,enabled:m.enabled!==false,weight:Number(m.weight)||1,max_inflight:Number(m.max_inflight)||1}))}
function channelStatus(text){document.getElementById('channels-status').textContent=text}
async function loadProviderHealth(){const el=document.getElementById('provider-health');if(!el)return;statusCache=[];channelHealth=new Map();anyRuntimeData=false;try{const r=await fetch('/api/v1/admin/provider-channels/status',{headers:adminHeaders()});if(!r.ok){el.innerHTML='';return}const caps=await r.json();const list=Array.isArray(caps)?caps:[];statusCache=list;const chm=new Map();let anyData=false;list.forEach(c=>{if(!c||!c.has_runtime_data)return;anyData=true;if(!c.snapshot||!Array.isArray(c.snapshot.channels))return;c.snapshot.channels.forEach(ch=>{if(!ch)return;const members=new Map();(ch.members||[]).forEach(mm=>{if(mm&&mm.id)members.set(mm.id,mm)});chm.set(ch.id,members)})});anyRuntimeData=anyData;channelHealth=chm;let ok=0,degraded=0;list.forEach(c=>{if(!c||!c.has_runtime_data||!c.snapshot||!Array.isArray(c.snapshot.channels))return;c.snapshot.channels.forEach(ch=>{if(!ch||!ch.enabled)return;if(ch.available)ok++;else degraded++})});if(!anyData||ok+degraded===0){el.innerHTML='<span class="muted">暂无运行数据</span>'}else if(degraded>0){el.innerHTML='<span class="pill bad">部分服务降级</span>'}else{el.innerHTML='<span class="pill ok">服务正常</span>'}}catch(e){el.innerHTML=''}}
async function patchMembers(id,members){return fetch('/api/v1/admin/provider-channels/'+encodeURIComponent(id),{method:'PATCH',headers:adminHeaders(true),body:JSON.stringify({members})}).then(json)}
function fmtHealthTime(v){const t=new Date(v);return isNaN(t.getTime())?esc(String(v||'')):t.toLocaleString('zh-CN')}
function memberHealth(s){if(s.retired)return'<span class="pill bad">退休</span>';const cooling=!!s.half_open||(s.cooldown_until&&new Date(s.cooldown_until).getTime()>Date.now());if(cooling){const t=s.cooldown_until?fmtHealthTime(s.cooldown_until):'';return'<span class="pill warn">冷却中'+(t?' · '+t:'')+'</span>'}if(!(Number(s.failures)||0))return'<span class="pill ok">正常</span>';if(s.last_failure_retryable)return'<span class="pill warn">最近失败（可重试）</span>';return'<span class="pill bad">最近失败</span>'}
function healthMeta(s){const t=s.last_success_at?fmtHealthTime(s.last_success_at):'无记录';return'成功 '+(Number(s.successes)||0)+' · 失败 '+(Number(s.failures)||0)+' · 429 '+(Number(s.retryable_429)||0)+' · 5xx '+(Number(s.server_error_5xx)||0)+' · 延迟 '+(Number(s.latency_ms)||0)+' ms · 上次成功 '+t}
function memberHealthRow(c,m){const ch=channelHealth.get(c.id);if(!anyRuntimeData)return'<div class="member-health muted">暂无运行数据</div>';if(!ch)return'';const s=ch.get(m.id);if(!s)return'';return'<div class="member-health">'+memberHealth(s)+'</div><div class="member-meta muted">'+healthMeta(s)+'</div>'}
function renderChannels(items){channelCache=items;const el=document.getElementById('channels');if(!items.length){el.className='empty';el.textContent='还没有通道。左侧新增后会显示在这里。';return}el.className='cards';el.innerHTML=items.map(c=>'<article class="card" data-channel="'+esc(c.id)+'"><div class="cardtop"><div><b>'+esc(c.label)+'</b><div class="muted">'+esc(c.capability)+' · '+esc(c.provider_name)+' · '+esc(c.model||'未指定模型')+'</div></div><div class="cardactions"><span class="pill '+(c.enabled?'ok':'bad')+'">'+(c.enabled?'已启用':'已停用')+'</span><button type="button" class="ghost" data-act="test-channel">测试</button><button type="button" class="ghost" data-act="edit-channel">编辑</button><button type="button" class="ghost" data-act="toggle-channel">'+(c.enabled?'停用':'启用')+'</button><button type="button" class="ghost danger" data-act="delete-channel">删除</button></div></div><p class="muted" id="test-result-'+esc(c.id)+'"></p>'+(c.members||[]).map(m=>'<div class="member"><div class="memberline"><span>'+esc(m.label)+' · 权重 '+Number(m.weight||1)+' · 并发 '+Number(m.max_inflight||1)+' · '+(m.secret_ready?'Key 已配置':'缺少 Key')+'</span><button type="button" class="danger" data-act="remove-member" data-member="'+esc(m.id)+'">移除</button></div>'+memberHealthRow(c,m)+'</div>').join('')+'<div class="addkey"><button type="button" class="ghost" data-act="toggle-add">+ 添加 Key</button><div class="addform" hidden>'+keyFields('a-')+'<button type="button" data-act="save-key">写入 Hub 密钥库</button> <button type="button" class="ghost" data-act="cancel-key">取消</button></div><p class="muted cardstatus"></p></div></article>').join('')}
async function loadChannels(){channelStatus('');await loadProviderHealth();try{const items=await fetch('/api/v1/admin/provider-channels',{headers:adminHeaders()}).then(json);renderChannels(items||[])}catch(e){channelCache=[];const el=document.getElementById('channels');el.className='empty error';el.textContent='无法加载：'+e.message}}
let editingId=null;
async function saveChannel(event){event.preventDefault();const status=document.getElementById('form-status');const members=formMembers();const dup=duplicateLabel(members.map(m=>m.label));if(dup){status.textContent='Key 名称重复：'+dup+'；同一通道内每个 Key 需要不同名称。';return}status.textContent='正在安全保存…';if(editingId){await saveChannelPatch(status,members);return}const body={capability:document.getElementById('capability').value,label:document.getElementById('label').value.trim(),provider_name:document.getElementById('provider-name').value,endpoint:document.getElementById('endpoint').value.trim(),model:document.getElementById('model').value.trim(),enabled:true,route_order:0,members};try{await fetch('/api/v1/admin/provider-channels',{method:'POST',headers:adminHeaders(true),body:JSON.stringify(body)}).then(json);clearFormKeys();status.textContent='已保存；Key 不会再次显示。';await loadChannels()}catch(e){status.textContent='保存失败：'+e.message}}
async function testChannel(card,channel){const el=document.getElementById('test-result-'+channel.id);if(!el)return;el.textContent='正在测试…';try{const r=await fetch('/api/v1/admin/provider-channels/'+encodeURIComponent(channel.id)+'/test',{method:'POST',headers:adminHeaders()});const d=await json(r);if(d&&d.model_responded){el.textContent='✓ 模型已响应 · '+(d.model_name||'未知模型')+' · '+(Number(d.latency_ms)||0)+'ms'}else{el.textContent='✗ '+((d&&d.message)||'测试失败')}}catch(e){el.textContent='✗ '+e.message}}
async function addChannelKey(card,channel){const form=card.querySelector('.addform');const status=card.querySelector('.cardstatus');const label=form.querySelector('.a-label').value.trim();const key=form.querySelector('.a-key').value.trim();if(!label||!key){status.textContent='请填写 Key 名称和 API Key。';return}const members=memberPatches(channel);const dup=duplicateLabel(members.map(m=>m.label).concat([label]));if(dup){status.textContent='Key 名称重复：'+dup+'；同一通道内每个 Key 需要不同名称。';return}members.push({label,api_key:key,enabled:true,weight:Number(form.querySelector('.a-weight').value)||1,max_inflight:Number(form.querySelector('.a-inflight').value)||1});status.textContent='正在安全写入…';try{await patchMembers(channel.id,members);form.querySelector('.a-key').value='';await loadChannels();channelStatus('已写入 Key「'+label+'」；Key 不会再次显示。')}catch(e){status.textContent='添加失败：'+e.message}}
async function removeChannelKey(card,channel,memberID){const status=card.querySelector('.cardstatus');const members=memberPatches(channel).filter(m=>m.id!==memberID);if(!members.length){status.textContent='通道至少需要保留一个 Key；如果整个通道不再使用，请停用或删除通道。';return}if(!confirm('移除后这个 Key 立即退出调度，且不会再显示。确定移除？'))return;status.textContent='正在移除…';try{await patchMembers(channel.id,members);await loadChannels();channelStatus('已移除该 Key，其余 Key 保持不变。')}catch(e){status.textContent='移除失败：'+e.message}}
// --- management ---
function openDialog(id){const d=document.getElementById(id);if(d&&typeof d.showModal==='function')d.showModal()}
function closeDialog(id){const d=document.getElementById(id);if(d&&typeof d.close==='function')d.close()}
function openCreate(){editingId=null;const form=document.getElementById('channel-form');form.reset();endpointTouched=false;document.getElementById('capability').disabled=false;document.getElementById('dialog-title').textContent='新增模型通道';applyEndpointPreset();openDialog('provider-dialog');const l=document.getElementById('label');if(l)l.focus()}
function openEdit(id){const c=(channelCache||[]).find(x=>x.id===id);if(!c)return;editingId=id;endpointTouched=true;document.getElementById('dialog-title').textContent='编辑通道';document.getElementById('capability').value=c.capability;document.getElementById('capability').disabled=true;document.getElementById('provider-name').value=c.provider_name||'';document.getElementById('label').value=c.label||'';document.getElementById('endpoint').value=c.endpoint||'';document.getElementById('model').value=c.model||'';syncProviderOptions();const form=document.getElementById('channel-form');const rows=form.querySelectorAll('.memberrow');rows.forEach(function(r,i){if(i>0)r.remove()});const keyRow=form.querySelector('.memberrow');const fields=keyFields(keyRow);fields.label.value=(c.members&&c.members[0]?c.members[0].label:'primary');fields.key.value='';fields.key.placeholder='留空表示保留现有 Key';if(c.members&&c.members[0])keyRow.dataset.memberId=c.members[0].id;(c.members||[]).slice(1).forEach(function(){addMemberRow();const rs=form.querySelectorAll('.memberrow');const row=rs[rs.length-1];const f=keyFields(row);f.label.value='';f.key.value='';f.key.placeholder='留空表示保留现有 Key'});openDialog('provider-dialog')}
async function saveChannelPatch(status,members){const c=(channelCache||[]).find(x=>x.id===editingId)||{};const patch={};if(document.getElementById('label').value.trim()!==c.label)patch.label=document.getElementById('label').value.trim();if(document.getElementById('provider-name').value!==c.provider_name)patch.provider_name=document.getElementById('provider-name').value;if(document.getElementById('endpoint').value.trim()!==c.endpoint)patch.endpoint=document.getElementById('endpoint').value.trim();if(document.getElementById('model').value.trim()!==(c.model||''))patch.model=document.getElementById('model').value.trim();const memberIds=(c.members||[]).map(x=>x.id);const mChanges=members.some(function(m,i){const orig=c.members&&c.members[i];return !orig||orig.label!==m.label||(m.api_key&&m.api_key.length>0)});if(mChanges){patch.members=members.map(function(m,i){return {id:memberIds[i]||'',label:m.label,api_key:m.api_key}})}try{await fetch('/api/v1/admin/provider-channels/'+encodeURIComponent(editingId),{method:'PATCH',headers:adminHeaders(true),body:JSON.stringify(patch)}).then(json);closeDialog('provider-dialog');loadChannels()}catch(e){status.textContent='保存失败：'+e.message}}
async function toggleChannel(id){const c=(channelCache||[]).find(x=>x.id===id);if(!c)return;const action=c.enabled?'disable':'enable';try{await fetch('/api/v1/admin/provider-channels/'+encodeURIComponent(id)+'/'+action,{method:'POST',headers:adminHeaders()}).then(json);loadChannels()}catch(e){alert('无法'+(action==='disable'?'停用':'启用')+'通道：'+e.message)}}
async function deleteChannel(id){const c=(channelCache||[]).find(x=>x.id===id);if(!c)return;if(!confirm('删除通道「'+c.label+'」？其存储的 Key 会被销毁，且该名称当前无法复用。'))return;try{await fetch('/api/v1/admin/provider-channels/'+encodeURIComponent(id),{method:'DELETE',headers:adminHeaders()}).then(json);loadChannels()}catch(e){alert('删除失败：'+e.message)}}
document.getElementById('channels').addEventListener('click',function(e){const btn=e.target.closest('[data-act]');if(!btn)return;const card=btn.closest('[data-channel]'),cid=card&&card.dataset.channel;if(!cid)return;const act=btn.dataset.act;const channel=(channelCache||[]).find(x=>x.id===cid);if(act==='edit-channel')openEdit(cid);else if(act==='toggle-channel')toggleChannel(cid);else if(act==='delete-channel')deleteChannel(cid);else if(act==='test-channel')testChannel(card,channel);else if(act==='add-key'){const f=card.querySelector('.keyform');if(f){f.hidden=false;f.querySelector('.a-label').focus()}}else if(act==='cancel-key'){const f=card.querySelector('.keyform');if(f){f.hidden=true;card.querySelector('.cardstatus').textContent=''}}else if(act==='save-key'){addChannelKey(card,channel)}else if(act==='remove-member'){removeChannelKey(card,channel,btn.dataset.member)}});
document.getElementById('new-channel-btn').addEventListener('click',openCreate);
document.getElementById('quick-config-btn').addEventListener('click',openQuick);
document.getElementById('refresh-channels').addEventListener('click',loadChannels);
document.querySelectorAll('[data-close="provider-dialog"]').forEach(function(b){b.addEventListener('click',function(){closeDialog('provider-dialog')})});
document.querySelectorAll('[data-close="quick-dialog"]').forEach(function(b){b.addEventListener('click',function(){closeDialog('quick-dialog')})});
document.getElementById('capability').addEventListener('change',syncProviderOptions);syncProviderOptions();
document.getElementById('provider-name').addEventListener('change',applyEndpointPreset);
document.getElementById('endpoint').addEventListener('input',function(){endpointTouched=true});
loadChannels();window.addEventListener('timingdex:admin-auth-changed',loadChannels);

document.getElementById('login-prompt').addEventListener('click',function(){const f=document.querySelector('.shell-auth input');if(f)f.focus()});
window.addEventListener('timingdex:admin-auth-changed',function(){const state=fetch('/api/v1/auth/admin/session').then(function(r){document.getElementById('auth-callout').hidden=r.ok})});
</script></body></html>`
