package api

// The channel manager is the only place a Provider key is ever entered, so the
// page is written against three boundaries that are easy to lose in an edit:
//
//   - A key exists in the browser only as the live value of a password input.
//     It is never stored (no localStorage/sessionStorage), never placed in a
//     URL or query string, never logged, and never rendered back: the admin
//     API blanks secret_ref and returns no api_key, so a re-render after a
//     successful write cannot echo one. Every key input is cleared on success.
//   - PATCH /api/v1/admin/provider-channels/{id} replaces the whole member set
//     (app.UpdateProviderChannel assigns channel.Members from the patch), and a
//     member is matched to its stored secret by id first, label second. So the
//     add/remove affordances resend *every* surviving member with its id and
//     without api_key — that is what preserves the already-stored keys of the
//     other members. Sending only the new member would drop the rest.
//   - Two members of one channel must not share a label. A new member carrying
//     an existing member's label is matched by that label on the server, which
//     would overwrite the older member's secret before the duplicate member id
//     fails the write. The duplicate check below keeps that input out.
//   - Per-member health joins the status endpoint's MemberStatus to a config
//     member row by id: both sides carry the provider_channel_members row id,
//     so the match is exact. A member the executor filters out (disabled, or
//     no stored secret) simply has no status row and renders no health line.
const providersHTML = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Timingdex · 模型服务</title><style>

.head-actions{display:flex;gap:10px}
.formgrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.wide{grid-column:1/-1}
.cards{display:grid;gap:10px}
.panel{padding:18px}
.cardtop{display:flex;justify-content:space-between;gap:12px;align-items:center}
.card{padding:15px}
.member{margin-top:9px;padding-top:9px;border-top:1px solid var(--rule);color:var(--text-muted);font-size:12px}
.memberline{display:flex;gap:10px;align-items:center;justify-content:space-between}
.keyhead{display:flex;justify-content:space-between;align-items:center;margin:16px 0 8px}
.keyhead b{font-size:12px;font-weight:800;letter-spacing:.1em;color:var(--text-muted)}
.cardactions{display:flex;gap:8px;align-items:center}
.memberrow{border:1px solid var(--rule);border-radius:10px;background:var(--surface);padding:12px;margin-bottom:10px}
.rowtop{display:flex;justify-content:space-between;align-items:center;margin-bottom:9px}
.rowtop b{font-size:12px;color:var(--text)}
.addkey{margin-top:12px;padding-top:11px;border-top:1px solid var(--rule)}
.addform{margin-top:10px}
.advanced-config{border:1px solid var(--rule);border-radius:10px;background:var(--surface);margin-top:10px;padding:10px 12px}
.advanced-config summary{cursor:pointer;font-size:12px;font-weight:800;color:var(--text-muted);user-select:none}
.advanced-config .formgrid{grid-template-columns:1fr 1fr;gap:10px}
.provider-health{display:flex;align-items:center;gap:8px;margin:0 0 12px;min-height:16px}
.member-health{display:flex;align-items:center;gap:8px;margin-top:7px}
.member-meta{margin-top:5px;font-size:11px}
.probe-row{display:flex;gap:8px;align-items:center}
.probe-row input{flex:1}
.probe-row button{white-space:nowrap}
label{display:block;font-size:12px;font-weight:800;color:var(--text-muted);margin:0 0 6px}
.empty.error{color:var(--ev-contradicted)}
@media(max-width:760px){.formgrid{grid-template-columns:1fr}
.wrap{padding:28px 18px}
}

</style></head><body><!--SHELL_HEADER--><main class="wrap"><div class="head"><div><div class="eyebrow">模型</div><h1>模型服务</h1><p class="muted">给每个功能配一个模型服务。一个服务可放多个密钥，自动轮换；某个密钥用量用完或临时失败时，自动换下一个。</p></div><div class="head-actions"><button type="button" class="primary" id="new-channel-btn">新增模型</button><button type="button" class="ghost" id="quick-config-btn">一键配置</button><button type="button" class="ghost" id="refresh-channels">刷新</button></div></div><div class="auth-callout" id="auth-callout" hidden>需要 Hub 管理口令才能查看与配置模型。<button type="button" id="login-prompt">登录以查看</button></div><p class="muted">口令只留在当前页面，不写入浏览器存储。密钥通过管理员加密请求存入 Hub 的加密库，页面不回显。</p><div class="callout callout--attention" id="admin-auth-callout" hidden><span>这台 Hub 当前对内网免口令：可信网段里的任何设备都能读写这里的模型配置。要改成必须输入口令，把 hub_security.admin_auth 设为 "required"。</span></div><section class="panel"><div class="cardtop"><h2>路由</h2></div><div id="routing" class="muted">加载中…</div></section><section class="panel"><div class="cardtop"><h2>已配置的模型</h2><div class="tag-row"><span class="tag">视频理解</span><span class="tag">语音转文字</span><span class="tag">语义搜索</span><span class="tag">自动打标签</span><span class="tag">方案助手</span></div></div><p class="provider-health" id="provider-health"></p><p id="channels-status" class="muted"></p><div id="channels" class="empty">加载中…</div></section></main>
<dialog id="provider-dialog" class="ui-dialog"><button type="button" class="ui-dialog__close" data-close="provider-dialog" aria-label="关闭">×</button><h3 id="dialog-title">新增模型</h3><form id="channel-form" onsubmit="saveChannel(event)"><div class="formgrid">
<div><label for="capability">功能</label><select id="capability"><option value="video_analysis">视频理解</option><option value="asr">语音转文字</option><option value="embedding">语义搜索</option><option value="tag_curator">自动打标签</option><option value="repurpose">方案助手</option></select></div>
<div><label for="provider-name">Provider</label><select id="provider-name"></select></div>
<div><label for="label">名字</label><input id="label" required placeholder="例如 Gemini 主账号"></div><div><label for="model">模型</label><div class="probe-row"><input id="model" placeholder="模型 ID" list="model-options"><datalist id="model-options"></datalist><button type="button" class="ghost" id="probe-models" onclick="probeModels()">看看有哪些模型</button></div></div>
<div><label for="route-order">顺序（fallback 优先级）</label><input id="route-order" type="number" min="0" value="0"></div><div class="wide"><label for="endpoint">服务地址</label><input id="endpoint" placeholder="https://…"></div>
</div>
<div class="keyhead"><b>密钥列表</b><button type="button" class="ghost" onclick="addMemberRow()">+ 再加一个密钥</button></div>
<div id="member-rows"><div class="memberrow"><div class="rowtop"><b>默认密钥</b></div><div class="formgrid">
<div><label for="member-label">密钥名称</label><input id="member-label" class="m-label" value="primary" required></div><div><label for="api-key">密钥</label><input id="api-key" class="m-key" type="password" autocomplete="new-password" required></div>
</div><details class="advanced-config wide"><summary>高级设置</summary><div class="formgrid"><div><label for="weight">优先顺序</label><input id="weight" aria-label="优先顺序" class="m-weight" type="number" min="1" value="1"></div><div><label for="max-inflight">同时用几个</label><input id="max-inflight" aria-label="同时用几个" class="m-inflight" type="number" min="1" value="1"></div></div></details>
</div></div></div>
<button type="submit">保存</button><p id="form-status" class="muted"></p></form></dialog>
<dialog id="quick-dialog" class="ui-dialog"><button type="button" class="ui-dialog__close" data-close="quick-dialog" aria-label="关闭">×</button><h3 id="quick-dialog-title">一键配置模型</h3><p class="muted">常用服务只填密钥：地址和模型都已预置好。自己的服务：填服务地址 + 密钥，程序自动看看它有哪些模型，你再勾选它负责哪个功能。</p><div class="keyhead"><b>常用服务</b></div><div id="quick-rows"></div><div class="keyhead" style="margin-top:18px"><b>自己的服务</b></div><div class="memberrow" id="custom-row"><div class="formgrid"><div><label>服务地址</label><input id="custom-endpoint" placeholder="https://…（OpenAI 兼容）"></div><div><label>密钥</label><input id="custom-key" type="password" autocomplete="new-password" placeholder="粘贴密钥"></div></div><div class="memberline" style="margin-top:10px"><span id="custom-probe-status" class="muted">还没查看</span><button type="button" class="ghost" onclick="customProbe()">看看有哪些模型</button></div><div id="custom-roles" class="member muted" style="margin-top:8px"></div></div><button type="button" id="quick-go" onclick="quickSubmit()">一键配好</button><p id="quick-status" class="muted"></p></dialog>
<script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const providerOptions={video_analysis:[['gemini','Gemini'],['qwen_video','千问视频'],['volcengine_video','火山视频'],['local_vlm','本地 VLM']],asr:[['stepfun','StepFun'],['qwen','千问 ASR'],['volcengine_asr','火山 ASR']],embedding:[['openai_embeddings','OpenAI-compatible Embeddings'],['gemini_embed_content','Gemini Embeddings'],['volc_agent_plan_embedding','火山 Agent Plan Embeddings'],['volc_coding_plan_embedding','火山 Coding Plan Embeddings']],tag_curator:[['openai_chat','OpenAI-compatible Chat'],['volc_agent_plan','火山 Agent Plan'],['volc_coding_plan','火山 Coding Plan']],repurpose:[['openai_chat','OpenAI-compatible Chat']]};
// Well-known base URLs so the operator only types the key. These mirror the
// shipped config.example.json defaults; a provider with no entry leaves the
// endpoint blank (generic OpenAI-compatible, local, or account-specific).
const endpointPresets={gemini:'https://generativelanguage.googleapis.com/v1beta',gemini_embed_content:'https://generativelanguage.googleapis.com/v1beta',qwen:'https://dashscope.aliyuncs.com/compatible-mode/v1',qwen_video:'https://dashscope.aliyuncs.com/compatible-mode/v1',volcengine_video:'https://ark.cn-beijing.volces.com/api/v3',volc_agent_plan:'https://ark.cn-beijing.volces.com/api/plan/v3',volc_coding_plan:'https://ark.cn-beijing.volces.com/api/coding/v3',volc_agent_plan_embedding:'https://ark.cn-beijing.volces.com/api/plan/v3',volc_coding_plan_embedding:'https://ark.cn-beijing.volces.com/api/coding/v3',stepfun:'https://api.stepfun.com/step_plan/v1',local_vlm:'http://127.0.0.1:8080/v1'};
// endpointTouched separates an auto-filled preset (safe to replace when the
// provider changes) from an operator-typed endpoint (never clobbered).
let endpointTouched=false;
function applyEndpointPreset(){const provider=document.getElementById('provider-name').value;const el=document.getElementById('endpoint');if(!provider||!el||endpointTouched)return;el.value=endpointPresets[provider]||''}
// probeModels is the one-click model-list read: it sends the still-open form's
// endpoint and key to the Hub, which makes one non-billed GET {endpoint}/models
// and returns the model ids (redacted, never echoed back). The key goes no
// further than the same admin HTTPS direction it already travels on save.
function probeModels(){const status=document.getElementById('form-status');const provider=document.getElementById('provider-name').value;const endpoint=document.getElementById('endpoint').value.trim();const keyField=document.querySelector('#member-rows .memberrow .m-key');const key=keyField?keyField.value.trim():'';if(!endpoint){status.textContent='请先填服务地址。';return}if(!key){status.textContent='先填一个密钥，再看看有哪些模型。';return}status.textContent='正在查看模型…';fetch('/api/v1/admin/provider-channels/probe-models',{method:'POST',headers:adminHeaders(true),body:JSON.stringify({provider_name:provider,endpoint:endpoint,api_key:key})}).then(json).then(function(d){const dl=document.getElementById('model-options');dl.innerHTML=(d.models||[]).map(m=>'<option value="'+esc(m)+'"></option>').join('');const model=document.getElementById('model');if(d&&d.models&&d.models.length){if(!model.value.trim())model.value=d.models[0];status.textContent='✓ 有 '+d.models.length+' 个模型，可下拉选择或直接输入。'}else{status.textContent='✗ '+((d&&d.message)||'未读到模型列表')}}).catch(function(e){status.textContent='✗ '+e.message})}
// --- 一键配置：Plan 预设 + 自定义端点 ---
// Plan 行只填 Key：端点与模型已探明并写死，用户不需要读 model list。
// 自定义端点：填 Endpoint + Key，程序探测可用模型，用户勾选该端点担当的角色。
// 两个来源可以并存：Plan 键和自定义端点各自补上缺失的能力（跨 plan 混用）。
const modelPresets={stepfun:'stepaudio-2.5-asr',qwen:'qwen3-asr-flash',gemini:'gemini-2.5-flash',qwen_video:'qwen3.6-flash',volcengine_video:'doubao-1.5-vision-pro-250428',local_vlm:'Qwen3-VL-4B-Instruct',volc_agent_plan:'doubao-seed-2.0-lite',volc_coding_plan:'ark-code-latest',volc_agent_plan_embedding:'doubao-embedding-vision-251215',volc_coding_plan_embedding:'doubao-embedding-vision-251215'};
const capNames={video_analysis:'视频理解',asr:'语音转文字',repurpose:'方案助手',tag_curator:'自动打标签',embedding:'语义搜索'};
const planPresets=[
 {id:'volc_agent_plan',name:'火山 Agent Plan',channels:[
   {cap:'repurpose',provider:'volc_agent_plan',endpoint:'https://ark.cn-beijing.volces.com/api/plan/v3',model:'doubao-seed-2.0-lite'},
   {cap:'tag_curator',provider:'volc_agent_plan',endpoint:'https://ark.cn-beijing.volces.com/api/plan/v3',model:'doubao-seed-2.0-lite'},
   {cap:'embedding',provider:'volc_agent_plan_embedding',endpoint:'https://ark.cn-beijing.volces.com/api/plan/v3',model:'doubao-embedding-vision-251215'},
 ]},
 {id:'volc_coding_plan',name:'火山 Coding Plan',channels:[
   {cap:'repurpose',provider:'volc_coding_plan',endpoint:'https://ark.cn-beijing.volces.com/api/coding/v3',model:'ark-code-latest'},
   {cap:'tag_curator',provider:'volc_coding_plan',endpoint:'https://ark.cn-beijing.volces.com/api/coding/v3',model:'ark-code-latest'},
   {cap:'embedding',provider:'volc_coding_plan_embedding',endpoint:'https://ark.cn-beijing.volces.com/api/coding/v3',model:'doubao-embedding-vision-251215'},
 ]},
 {id:'qwen_token_plan',name:'Qwen Token Plan',channels:[
   {cap:'repurpose',provider:'openai_chat',endpoint:'https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1',model:'qwen3.7-plus'},
   {cap:'tag_curator',provider:'openai_chat',endpoint:'https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1',model:'qwen3.7-plus'},
 ]},
 {id:'asr',name:'语音转文字（StepFun）',channels:[
   {cap:'asr',provider:'stepfun',endpoint:'https://api.stepfun.com/step_plan/v1',model:'stepaudio-2.5-asr'},
 ]},
];
function quickCapConfigured(cap){return (channelCache||[]).some(function(c){return c.capability===cap})}
function quickChannelRowHTML(ch){return '<div class="member muted" style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:6px"><span style="min-width:118px">'+esc(capNames[ch.cap])+'</span><span style="display:flex;align-items:center;gap:6px;flex:1;min-width:180px"><label style="margin:0;white-space:nowrap">模型</label><input class="q-model" data-cap="'+ch.cap+'" value="'+esc(ch.model)+'" placeholder="模型 ID（可自定义）"></span><span style="display:flex;align-items:center;gap:6px;flex:2;min-width:240px"><label style="margin:0;white-space:nowrap">服务地址</label><input class="q-endpoint" data-cap="'+ch.cap+'" value="'+esc(ch.endpoint)+'"></span></div>'}
function quickPlanRowHTML(plan){return '<div class="memberrow" data-plan="'+plan.id+'"><div class="rowtop"><b>'+esc(plan.name)+'</b><span class="pill" data-status></span></div><div class="formgrid"><div><label>密钥</label><input class="q-key" type="password" autocomplete="new-password" placeholder="粘贴密钥（留空跳过）"></div></div><div class="keyhead" style="margin:10px 0 4px"><b>将配置的功能（模型已预填，可改）</b></div>'+plan.channels.map(quickChannelRowHTML).join('')+'</div>'}
function quickRender(){const container=document.getElementById('quick-rows');container.innerHTML=planPresets.map(quickPlanRowHTML).join('');planPresets.forEach(function(plan){const row=container.querySelector('[data-plan="'+plan.id+'"]');const missing=plan.channels.filter(function(ch){return !quickCapConfigured(ch.cap)});const status=row.querySelector('[data-status]');if(missing.length===0){status.className='pill ok';status.textContent='已配置';row.dataset.configured='1';row.querySelector('.q-key').disabled=true}else if(missing.length<plan.channels.length){status.className='pill warn';status.textContent='部分已配置'}else{status.className='pill bad';status.textContent='未配置'}})}
async function openQuick(){await loadChannels();document.getElementById('quick-dialog-title').textContent='一键配置模型';quickRender();customReset();const d=document.getElementById('quick-dialog');if(d&&typeof d.showModal==='function')d.showModal()}
// 自定义端点：程序探测可用模型，用户勾选角色（不填模型名）。
let customModels=[];let customProbed=false;
const customRoles=[['repurpose','方案助手'],['tag_curator','自动打标签'],['embedding','语义搜索'],['video_analysis','视频理解']];
function customReset(){customModels=[];customProbed=false;const roles=document.getElementById('custom-roles');if(roles)roles.innerHTML='';const st=document.getElementById('custom-probe-status');if(st)st.textContent='还没查看'}
async function customProbe(){const st=document.getElementById('custom-probe-status');const endpoint=document.getElementById('custom-endpoint').value.trim();const key=document.getElementById('custom-key').value.trim();if(!endpoint){st.textContent='请先填服务地址';return}if(!key){st.textContent='请先填密钥';return}st.textContent='正在探测…';try{const d=await fetch('/api/v1/admin/provider-channels/probe-models',{method:'POST',headers:adminHeaders(true),body:JSON.stringify({provider_name:'openai_chat',endpoint:endpoint,api_key:key})}).then(json);customModels=d.models||[];customProbed=true;const roles=document.getElementById('custom-roles');roles.innerHTML='<div class="muted" style="margin-bottom:6px">可用模型 '+customModels.length+' 个：'+esc(customModels.slice(0,6).join('、'))+(customModels.length>6?'…':'')+'</div>'+customRoles.map(function(r){const disabled=quickCapConfigured(r[0]);return '<div style="display:flex;gap:8px;align-items:center;margin:4px 0;flex-wrap:wrap"><label style="display:flex;gap:8px;align-items:center;min-width:150px"><input type="checkbox" class="q-role" data-cap="'+r[0]+'"'+(disabled?' disabled':'')+'>'+esc(r[1])+(disabled?'（已配置）':'')+'</label><input class="q-role-model" data-cap="'+r[0]+'" value="'+esc(customRoleModel(r[0]))+'" placeholder="模型 ID（可自定义）" style="flex:1;min-width:200px"></div>'}).join('');if(d&&d.status!=='ok'){st.textContent='⚠ '+((d&&d.message)||'未读到模型');return}st.textContent='✓ 有 '+customModels.length+' 个模型，勾选负责的功能'}catch(e){st.textContent='✗ '+e.message;customProbed=false}}
function customRoleModel(cap){const list=customModels||[];if(!list.length)return '';if(cap==='embedding'){const emb=list.find(function(m){return /embed/i.test(m)});if(emb)return emb}if(cap==='repurpose'||cap==='tag_curator'){const chat=list.find(function(m){return !/image|embed|tts|audio/i.test(m)});if(chat)return chat}return list[0]}
function customRoleProtocol(cap){return cap==='embedding'?'openai_embeddings':(cap==='video_analysis'?'openai_video':'openai_chat')}
async function quickSubmit(){const btn=document.getElementById('quick-go');btn.disabled=true;const status=document.getElementById('quick-status');const created=[];const errors=[];let ok=true;const rows=[...document.querySelectorAll('#quick-rows .memberrow')];for(const row of rows){if(row.dataset.configured)continue;const plan=planPresets.find(function(p){return p.id===row.dataset.plan});const key=row.querySelector('.q-key').value.trim();if(!key)continue;for(const ch of plan.channels){if(quickCapConfigured(ch.cap))continue;const chEndpoint=((row.querySelector('.q-endpoint[data-cap="'+ch.cap+'"]')||{}).value||'').trim();const chModel=((row.querySelector('.q-model[data-cap="'+ch.cap+'"]')||{}).value||'').trim();try{const body={capability:ch.cap,label:plan.name,provider_name:ch.provider,endpoint:chEndpoint||ch.endpoint,model:chModel||ch.model,enabled:true,route_order:0,members:[{label:'primary',api_key:key,enabled:true,weight:1,max_inflight:1}]};await fetch('/api/v1/admin/provider-channels',{method:'POST',headers:adminHeaders(true),body:JSON.stringify(body)}).then(json);created.push(capNames[ch.cap]||ch.cap)}catch(e){errors.push((capNames[ch.cap]||ch.cap)+' '+e.message);ok=false}}}
const cep=document.getElementById('custom-endpoint').value.trim();const cek=document.getElementById('custom-key').value.trim();if(cep&&cek){const checked=[...document.querySelectorAll('#custom-roles .q-role:checked')];if(checked.length&&!customProbed){status.textContent='正在探测自己的服务…';try{const d=await fetch('/api/v1/admin/provider-channels/probe-models',{method:'POST',headers:adminHeaders(true),body:JSON.stringify({provider_name:'openai_chat',endpoint:cep,api_key:cek})}).then(json);customModels=d.models||[];customProbed=true}catch(e){errors.push('自己的服务 '+e.message);ok=false}}for(const cb of checked){const cap=cb.dataset.cap;if(quickCapConfigured(cap))continue;const model=((document.querySelector('#custom-roles .q-role-model[data-cap="'+cap+'"]')||{}).value||'').trim()||customRoleModel(cap);if(!model){errors.push((capNames[cap]||cap)+' 未探测到模型');ok=false;continue}try{const body={capability:cap,label:'自定义端点',provider_name:customRoleProtocol(cap),endpoint:cep,model:model,enabled:true,route_order:0,members:[{label:'primary',api_key:cek,enabled:true,weight:1,max_inflight:1}]};await fetch('/api/v1/admin/provider-channels',{method:'POST',headers:adminHeaders(true),body:JSON.stringify(body)}).then(json);created.push(capNames[cap]||cap)}catch(e){errors.push((capNames[cap]||cap)+' '+e.message);ok=false}}}
document.querySelectorAll('#quick-rows .q-key').forEach(function(k){k.value=''});document.getElementById('custom-key').value='';status.textContent=created.length?('已配好 '+created.length+' 个功能'+(errors.length?'；失败：'+errors.join('；'):'')):(errors.length?'未配置：'+errors.join('；'):'没有要配的（没填密钥 / 没勾功能，或都配好了）');btn.disabled=false;await loadChannels();if(created.length&&!errors.length){closeDialog('quick-dialog')}}
let channelCache=[];let statusCache=[];let channelHealth=new Map();let anyRuntimeData=false;
function syncProviderOptions(){const capability=document.getElementById('capability').value;const select=document.getElementById('provider-name');const prior=select.value;select.innerHTML=(providerOptions[capability]||[]).map(([value,label])=>'<option value="'+value+'">'+label+'</option>').join('');if([...select.options].some(o=>o.value===prior))select.value=prior;applyEndpointPreset()}
 function csrfToken(){const prefix='__Host-timingdex_csrf=';const item=document.cookie.split('; ').find(function(x){return x.indexOf(prefix)===0});return item?decodeURIComponent(item.slice(prefix.length)):''}
 function adminHeaders(json=false){const headers={};const csrf=csrfToken();if(csrf)headers['X-CSRF-Token']=csrf;if(json)headers['Content-Type']='application/json';return headers}
async function apiErrMsg(r){try{const d=await r.json();if(d&&d.error&&d.error.message)return d.error.action?(d.error.message+'（'+d.error.action+'）'):d.error.message}catch(_){}return (await r.text()).trim()}
async function json(r){if(!r.ok)throw Error(await apiErrMsg(r));return r.status===204?null:r.json()}
function duplicateLabel(labels){const seen=new Set();for(const raw of labels){const key=String(raw||'').trim().toLowerCase();if(!key)continue;if(seen.has(key))return raw;seen.add(key)}return ''}
 function keyFields(prefix){return '<div class="formgrid"><div><label>密钥名称</label><input class="'+prefix+'label" aria-label="密钥名称" value="" required></div><div><label>密钥</label><input class="'+prefix+'key" aria-label="密钥" type="password" autocomplete="new-password" required></div></div><details class="advanced-config wide"><summary>高级设置</summary><div class="formgrid"><div><label>优先顺序</label><input class="'+prefix+'weight" aria-label="优先顺序" type="number" min="1" value="1"></div><div><label>同时用几个</label><input class="'+prefix+'inflight" aria-label="同时用几个" type="number" min="1" value="1"></div></div></details>'}
function addMemberRow(){const rows=document.getElementById('member-rows');const row=document.createElement('div');row.className='memberrow';row.innerHTML='<div class="rowtop"><b>追加密钥</b><button type="button" class="danger rowremove">移除这一行</button></div>'+keyFields('m-');rows.appendChild(row);const label=row.querySelector('.m-label');label.value='key-'+rows.children.length;row.querySelector('.rowremove').addEventListener('click',()=>row.remove());label.focus()}
function formMembers(){return [...document.querySelectorAll('#member-rows .memberrow')].map(row=>({label:row.querySelector('.m-label').value.trim(),api_key:row.querySelector('.m-key').value.trim(),enabled:true,weight:Number(row.querySelector('.m-weight').value)||1,max_inflight:Number(row.querySelector('.m-inflight').value)||1}))}
function clearFormKeys(){document.querySelectorAll('#member-rows .m-key').forEach(input=>{input.value=''});[...document.querySelectorAll('#member-rows .memberrow')].slice(1).forEach(row=>row.remove())}
function memberPatches(channel){return (channel.members||[]).map(m=>({id:m.id,label:m.label,enabled:m.enabled!==false,weight:Number(m.weight)||1,max_inflight:Number(m.max_inflight)||1}))}
function channelStatus(text){document.getElementById('channels-status').textContent=text}
async function loadProviderHealth(){const el=document.getElementById('provider-health');if(!el)return;statusCache=[];channelHealth=new Map();anyRuntimeData=false;try{const r=await fetch('/api/v1/admin/provider-channels/status',{headers:adminHeaders()});if(!r.ok){el.innerHTML='';return}const caps=await r.json();const list=Array.isArray(caps)?caps:[];statusCache=list;const chm=new Map();let anyData=false;list.forEach(c=>{if(!c||!c.has_runtime_data)return;anyData=true;if(!c.snapshot||!Array.isArray(c.snapshot.channels))return;c.snapshot.channels.forEach(ch=>{if(!ch)return;const members=new Map();(ch.members||[]).forEach(mm=>{if(mm&&mm.id)members.set(mm.id,mm)});chm.set(ch.id,members)})});anyRuntimeData=anyData;channelHealth=chm;let ok=0,degraded=0;list.forEach(c=>{if(!c||!c.has_runtime_data||!c.snapshot||!Array.isArray(c.snapshot.channels))return;c.snapshot.channels.forEach(ch=>{if(!ch||!ch.enabled)return;if(ch.available)ok++;else degraded++})});if(!anyData||ok+degraded===0){el.innerHTML='<span class="muted">还没有使用记录</span>'}else if(degraded>0){el.innerHTML='<span class="pill bad">部分服务降级</span>'}else{el.innerHTML='<span class="pill ok">服务正常</span>'}}catch(e){el.innerHTML=''}}
async function patchMembers(id,members){return fetch('/api/v1/admin/provider-channels/'+encodeURIComponent(id),{method:'PATCH',headers:adminHeaders(true),body:JSON.stringify({members})}).then(json)}
function fmtHealthTime(v){const t=new Date(v);return isNaN(t.getTime())?esc(String(v||'')):t.toLocaleString('zh-CN')}
function memberHealth(s){if(s.retired)return'<span class="pill bad">停用</span>';const cooling=!!s.half_open||(s.cooldown_until&&new Date(s.cooldown_until).getTime()>Date.now());if(cooling){const t=s.cooldown_until?fmtHealthTime(s.cooldown_until):'';return'<span class="pill warn">等待中'+(t?' · '+t:'')+'</span>'}if(!(Number(s.failures)||0))return'<span class="pill ok">正常</span>';if(s.last_failure_retryable)return'<span class="pill warn">最近失败（可重试）</span>';return'<span class="pill bad">最近失败</span>'}
function healthMeta(s){const t=s.last_success_at?fmtHealthTime(s.last_success_at):'无记录';return'成功 '+(Number(s.successes)||0)+' · 失败 '+(Number(s.failures)||0)+' · 限流 '+(Number(s.retryable_429)||0)+' · 服务端错误 '+(Number(s.server_error_5xx)||0)+' · 延迟 '+(Number(s.latency_ms)||0)+' 毫秒 · 上次成功 '+t}
function memberHealthRow(c,m){const ch=channelHealth.get(c.id);if(!anyRuntimeData)return'<div class="member-health muted">还没有使用记录</div>';if(!ch)return'';const s=ch.get(m.id);if(!s)return'';return'<div class="member-health">'+memberHealth(s)+'</div><div class="member-meta muted">'+healthMeta(s)+'</div>'}
function renderRouting(items){const el=document.getElementById('routing');if(!el)return;const caps=['video_analysis','asr','embedding','tag_curator','repurpose'];const names={video_analysis:'视频理解',asr:'语音转文字',embedding:'语义搜索',tag_curator:'自动打标签',repurpose:'方案助手'};const lines=caps.map(function(cap){const list=(items||[]).filter(function(c){return c.capability===cap&&c.enabled}).sort(function(a,b){return (a.route_order||0)-(b.route_order||0)});if(!list.length)return null;const chain=list.map(function(c,i){return (i===0?'':' → ')+esc(c.label||c.provider_name)}).join('');return '<div class="kv"><span class="k">'+names[cap]+'</span><span class="v">'+chain+'</span></div>'}).filter(Boolean);el.innerHTML=lines.length?lines.join(''):'<span class="muted">还没有启用的模型。</span>'}function renderChannels(items){channelCache=items;const el=document.getElementById('channels');if(!items.length){el.className='empty';el.textContent='还没有模型。左侧新增后会显示在这里。';return}el.className='cards';el.innerHTML=items.map(c=>'<article class="card" data-channel="'+esc(c.id)+'"><div class="cardtop"><div><b>'+esc(c.label)+'</b><div class="muted">'+esc(c.capability)+' · '+esc(c.provider_name)+' · '+esc(c.model||'没选模型')+'</div></div><div class="cardactions"><span class="pill '+(c.enabled?'ok':'bad')+'">'+(c.enabled?'已启用':'已停用')+'</span><button type="button" class="ghost" data-act="test-channel">试试能不能用</button><button type="button" class="ghost" data-act="edit-channel">编辑</button><button type="button" class="ghost" data-act="toggle-channel">'+(c.enabled?'停用':'启用')+'</button><button type="button" class="ghost danger" data-act="delete-channel">删除</button></div></div><p class="muted" id="test-result-'+esc(c.id)+'"></p>'+(c.members||[]).map(m=>'<div class="member"><div class="memberline"><span>'+esc(m.label)+' · 优先 '+Number(m.weight||1)+' · 同时 '+Number(m.max_inflight||1)+' · '+(m.secret_ready?'密钥已存':'缺密钥')+'</span><button type="button" class="danger" data-act="remove-member" data-member="'+esc(m.id)+'">移除</button></div>'+memberHealthRow(c,m)+'</div>').join('')+'<div class="addkey"><button type="button" class="ghost" data-act="toggle-add">+ 添加密钥</button><div class="addform" hidden>'+keyFields('a-')+'<button type="button" data-act="save-key">存入</button> <button type="button" class="ghost" data-act="cancel-key">取消</button></div><p class="muted cardstatus"></p></div></article>').join('')}
async function loadChannels(){channelStatus('');await loadProviderHealth();try{const items=await fetch('/api/v1/admin/provider-channels',{headers:adminHeaders()}).then(json);renderChannels(items||[]);renderRouting(items||[])}catch(e){channelCache=[];const el=document.getElementById('channels');el.className='empty error';el.textContent='无法加载：'+e.message}}
let editingId=null;
async function saveChannel(event){event.preventDefault();const status=document.getElementById('form-status');const members=formMembers();const dup=duplicateLabel(members.map(m=>m.label));if(dup){status.textContent='密钥名称重复：'+dup+'；同一模型内每个密钥需要不同名称。';return}status.textContent='正在安全保存…';if(editingId){await saveChannelPatch(status,members);return}const body={capability:document.getElementById('capability').value,label:document.getElementById('label').value.trim(),provider_name:document.getElementById('provider-name').value,endpoint:document.getElementById('endpoint').value.trim(),model:document.getElementById('model').value.trim(),enabled:true,route_order:Number(document.getElementById('route-order').value)||0,members};try{await fetch('/api/v1/admin/provider-channels',{method:'POST',headers:adminHeaders(true),body:JSON.stringify(body)}).then(json);clearFormKeys();status.textContent='已保存；密钥不会再次显示。';await loadChannels()}catch(e){status.textContent='保存失败：'+e.message}}
async function testChannel(card,channel){const el=document.getElementById('test-result-'+channel.id);if(!el)return;el.textContent='正在测试…';try{const r=await fetch('/api/v1/admin/provider-channels/'+encodeURIComponent(channel.id)+'/test',{method:'POST',headers:adminHeaders()});const d=await json(r);if(d&&d.model_responded){el.textContent='✓ 模型已响应 · '+(d.model_name||'未知模型')+' · '+(Number(d.latency_ms)||0)+'ms'}else{el.textContent='✗ '+((d&&d.message)||'测试失败')}}catch(e){el.textContent='✗ '+e.message}}
async function addChannelKey(card,channel){const form=card.querySelector('.addform');const status=card.querySelector('.cardstatus');const label=form.querySelector('.a-label').value.trim();const key=form.querySelector('.a-key').value.trim();if(!label||!key){status.textContent='请填写密钥名称和密钥。';return}const members=memberPatches(channel);const dup=duplicateLabel(members.map(m=>m.label).concat([label]));if(dup){status.textContent='密钥名称重复：'+dup+'；同一模型内每个密钥需要不同名称。';return}members.push({label,api_key:key,enabled:true,weight:Number(form.querySelector('.a-weight').value)||1,max_inflight:Number(form.querySelector('.a-inflight').value)||1});status.textContent='正在安全写入…';try{await patchMembers(channel.id,members);form.querySelector('.a-key').value='';await loadChannels();channelStatus('已写入密钥「'+label+'」；密钥不会再次显示。')}catch(e){status.textContent='添加失败：'+e.message}}
async function removeChannelKey(card,channel,memberID){const status=card.querySelector('.cardstatus');const members=memberPatches(channel).filter(m=>m.id!==memberID);if(!members.length){status.textContent='模型至少需要保留一个密钥；如果整个模型不再使用，请停用或删除模型。';return}if(!confirm('移除后这个密钥立刻失效，不再显示。确定移除？'))return;status.textContent='正在移除…';try{await patchMembers(channel.id,members);await loadChannels();channelStatus('已移除该密钥，其余密钥保持不变。')}catch(e){status.textContent='移除失败：'+e.message}}
// --- management ---
function openDialog(id){const d=document.getElementById(id);if(d&&typeof d.showModal==='function')d.showModal()}
function closeDialog(id){const d=document.getElementById(id);if(d&&typeof d.close==='function')d.close()}
function openCreate(){editingId=null;const form=document.getElementById('channel-form');form.reset();endpointTouched=false;document.getElementById('capability').disabled=false;document.getElementById('dialog-title').textContent='新增模型';applyEndpointPreset();openDialog('provider-dialog');const l=document.getElementById('label');if(l)l.focus()}
function openEdit(id){const c=(channelCache||[]).find(x=>x.id===id);if(!c)return;editingId=id;endpointTouched=true;document.getElementById('dialog-title').textContent='编辑模型';document.getElementById('capability').value=c.capability;document.getElementById('capability').disabled=true;document.getElementById('provider-name').value=c.provider_name||'';document.getElementById('label').value=c.label||'';document.getElementById('endpoint').value=c.endpoint||'';document.getElementById('model').value=c.model||'';document.getElementById('route-order').value=c.route_order||0;syncProviderOptions();const form=document.getElementById('channel-form');const rows=form.querySelectorAll('.memberrow');rows.forEach(function(r,i){if(i>0)r.remove()});const keyRow=form.querySelector('.memberrow');const fields=keyFields(keyRow);fields.label.value=(c.members&&c.members[0]?c.members[0].label:'primary');fields.key.value='';fields.key.placeholder='留空表示保留现有密钥';if(c.members&&c.members[0])keyRow.dataset.memberId=c.members[0].id;(c.members||[]).slice(1).forEach(function(){addMemberRow();const rs=form.querySelectorAll('.memberrow');const row=rs[rs.length-1];const f=keyFields(row);f.label.value='';f.key.value='';f.key.placeholder='留空表示保留现有密钥'});openDialog('provider-dialog')}
async function saveChannelPatch(status,members){const c=(channelCache||[]).find(x=>x.id===editingId)||{};const patch={};if(document.getElementById('label').value.trim()!==c.label)patch.label=document.getElementById('label').value.trim();if(document.getElementById('provider-name').value!==c.provider_name)patch.provider_name=document.getElementById('provider-name').value;if(document.getElementById('endpoint').value.trim()!==c.endpoint)patch.endpoint=document.getElementById('endpoint').value.trim();if(document.getElementById('model').value.trim()!==(c.model||''))patch.model=document.getElementById('model').value.trim();if((Number(document.getElementById('route-order').value)||0)!==(c.route_order||0))patch.route_order=Number(document.getElementById('route-order').value)||0;const memberIds=(c.members||[]).map(x=>x.id);const mChanges=members.some(function(m,i){const orig=c.members&&c.members[i];return !orig||orig.label!==m.label||(m.api_key&&m.api_key.length>0)});if(mChanges){patch.members=members.map(function(m,i){return {id:memberIds[i]||'',label:m.label,api_key:m.api_key}})}try{await fetch('/api/v1/admin/provider-channels/'+encodeURIComponent(editingId),{method:'PATCH',headers:adminHeaders(true),body:JSON.stringify(patch)}).then(json);closeDialog('provider-dialog');loadChannels()}catch(e){status.textContent='保存失败：'+e.message}}
async function toggleChannel(id){const c=(channelCache||[]).find(x=>x.id===id);if(!c)return;const action=c.enabled?'disable':'enable';try{await fetch('/api/v1/admin/provider-channels/'+encodeURIComponent(id)+'/'+action,{method:'POST',headers:adminHeaders()}).then(json);loadChannels()}catch(e){alert('无法'+(action==='disable'?'停用':'启用')+'模型：'+e.message)}}
async function deleteChannel(id){const c=(channelCache||[]).find(x=>x.id===id);if(!c)return;if(!confirm('删除模型「'+c.label+'」？其存储的密钥会被销毁，且该名称当前无法复用。'))return;try{await fetch('/api/v1/admin/provider-channels/'+encodeURIComponent(id),{method:'DELETE',headers:adminHeaders()}).then(json);loadChannels()}catch(e){alert('删除失败：'+e.message)}}
document.getElementById('channels').addEventListener('click',function(e){const btn=e.target.closest('[data-act]');if(!btn)return;const card=btn.closest('[data-channel]'),cid=card&&card.dataset.channel;if(!cid)return;const act=btn.dataset.act;const channel=(channelCache||[]).find(x=>x.id===cid);if(act==='edit-channel')openEdit(cid);else if(act==='toggle-channel')toggleChannel(cid);else if(act==='delete-channel')deleteChannel(cid);else if(act==='test-channel')testChannel(card,channel);else if(act==='add-key'){const f=card.querySelector('.keyform');if(f){f.hidden=false;f.querySelector('.a-label').focus()}}else if(act==='cancel-key'){const f=card.querySelector('.keyform');if(f){f.hidden=true;card.querySelector('.cardstatus').textContent=''}}else if(act==='save-key'){addChannelKey(card,channel)}else if(act==='remove-member'){removeChannelKey(card,channel,btn.dataset.member)}});
document.getElementById('new-channel-btn').addEventListener('click',openCreate);
document.getElementById('quick-config-btn').addEventListener('click',openQuick);
document.getElementById('refresh-channels').addEventListener('click',loadChannels);
document.querySelectorAll('[data-close="provider-dialog"]').forEach(function(b){b.addEventListener('click',function(){closeDialog('provider-dialog')})});
document.querySelectorAll('[data-close="quick-dialog"]').forEach(function(b){b.addEventListener('click',function(){closeDialog('quick-dialog')})});
document.getElementById('capability').addEventListener('change',syncProviderOptions);syncProviderOptions();
document.getElementById('provider-name').addEventListener('change',applyEndpointPreset);
document.getElementById('endpoint').addEventListener('input',function(){endpointTouched=true});
loadChannels();window.addEventListener('timingdex:admin-auth-changed',loadChannels);

document.getElementById('login-prompt').addEventListener('click',function(){const f=document.querySelector('.shell-auth input');if(f)f.focus()});
window.addEventListener('timingdex:admin-auth-changed',function(){const state=fetch('/api/v1/auth/admin/session').then(function(r){document.getElementById('auth-callout').hidden=r.ok})});
</script></body></html>`
