package api

// repurposeWorkspaceHTML is the /repurpose workspace.
const repurposeWorkspaceHTML = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NexusSlate · [[i18n:repurpose.title]]</title><style>

.head-actions{display:flex;gap:10px;align-items:center}
.repurpose-layout{display:grid;grid-template-columns:300px 1fr;gap:20px;align-items:start}
.plan-inbox{background:var(--surface);border:1px solid var(--rule);border-radius:14px;padding:14px;position:sticky;top:76px;max-height:calc(100vh - 100px);overflow:auto}
.plan-list{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:8px}
.plan-list .loading{color:var(--text-muted);font-size:13px;padding:10px 4px}
.plan-row{display:block;width:100%;height:auto;white-space:normal;text-align:left;padding:10px 12px;cursor:pointer;color:var(--text);font:inherit;border:1px solid var(--rule);border-radius:var(--r-md);background:var(--surface)}
.plan-row:hover{border-color:var(--rule-strong)}
.plan-row[aria-current="true"]{border-color:var(--brand);background:var(--nav-active)}
.plan-row .pl-title{font-weight:700;font-size:14px;margin-bottom:3px}
.plan-row .pl-meta{color:var(--text-muted);font-size:12px;display:flex;gap:8px;flex-wrap:wrap}
.plan-workspace{min-width:0}
.plan-titlebar{display:flex;gap:14px;justify-content:space-between;align-items:flex-start;flex-wrap:wrap;margin-bottom:14px}
.plan-title-row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.plan-titlebar h2{font-size:clamp(20px,3vw,30px);margin:0;letter-spacing:.01em}
.plan-id-row{display:flex;gap:8px;align-items:center;margin-top:8px}
.plan-id-row code{font-family:var(--font-data);font-size:12px;color:var(--text-muted);background:var(--inset);border:1px solid var(--rule);border-radius:6px;padding:3px 8px}
.plan-titlebar-actions{display:flex;gap:8px}
.plan{background:var(--surface);border:1px solid var(--rule);border-radius:14px;padding:18px}
.section{border:1px solid var(--rule);border-radius:12px;padding:14px;margin-bottom:14px;background:var(--inset)}
.sectionhead{display:flex;gap:10px;justify-content:space-between;align-items:flex-start;flex-wrap:wrap}
.role{font-weight:800;color:var(--text)}
.rationale{color:var(--text-muted);font-size:13px;margin:4px 0 10px}
.candidates{display:flex;flex-direction:column;gap:8px}
.candidates .candidate-card{margin-bottom:0}
.candidate-card{display:flex;gap:12px;align-items:flex-start;padding:10px 12px}
.candidate-card.selected{border-color:var(--ev-confirmed)}
.candidate-card.excluded{opacity:.55}
.candidate-card .thumb{width:150px;border-radius:8px;flex:none}
.candidate-card .cand-body{flex:1;min-width:0}
.candidate-card .cand-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}
.small{color:var(--text-muted);font-size:12px}
.plan-command-bar{display:flex;gap:12px;justify-content:space-between;align-items:center;margin-top:16px;padding-top:14px;border-top:1px solid var(--rule);flex-wrap:wrap}
.plan-command-bar .cmd-actions{display:flex;gap:10px}
.status{display:inline;padding:0;border:0;background:transparent;color:var(--text-muted);font-size:13px}
.error{display:none;color:var(--ev-contradicted);font-size:13px;margin-top:8px;padding:0;border:0;background:transparent}
.error:not(:empty){display:block}
.revision-list{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:8px}
.revision-row{display:block;width:100%;height:auto;white-space:normal;text-align:left;padding:10px 12px;cursor:pointer;color:var(--text);font:inherit;border:1px solid var(--rule);border-radius:var(--r-md);background:var(--surface)}
.revision-row[aria-current="true"]{border-color:var(--brand)}
.revision-row .rv-meta{color:var(--text-muted);font-size:12px;margin-top:3px}
.revision-row .rv-note{color:var(--text-muted);font-size:13px;margin-top:4px}
.ui-dialog{background:var(--surface);color:var(--text);border:1px solid var(--rule-strong);border-radius:14px;padding:20px;width:min(680px,92vw);max-height:86vh;overflow:auto}
.ui-dialog::backdrop{background:rgba(6,12,24,.6)}
.ui-dialog h3{margin:0 0 12px}
.ui-dialog .field{margin-bottom:12px}
.ui-dialog label{display:block;color:var(--text-muted);font-size:13px;margin-bottom:4px}
.ui-dialog .row{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px}
.ui-dialog .dialog-actions{display:flex;gap:10px;justify-content:flex-end;margin-top:16px}
.dialog-close{position:absolute;top:12px;right:14px;background:transparent;border:none;color:var(--text-muted);font-size:20px;cursor:pointer}
.ui-dialog--media{width:min(860px,94vw)}
.shot-video{width:100%;border-radius:10px;background:var(--inset)}
.shot-dialog-meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px;color:var(--text-muted);font-size:13px}
.shot-dialog-meta b{color:var(--text)}
@media(max-width:900px){.repurpose-layout{grid-template-columns:1fr}
.plan-inbox{position:static;max-height:none}
.ui-dialog .row{grid-template-columns:1fr}
}
@media(max-width:600px){.candidate-card{flex-direction:column}
.candidate-card .thumb{width:100%}
.plan-command-bar{flex-direction:column;align-items:stretch}
.plan-command-bar .cmd-actions{justify-content:stretch}
.plan-command-bar .btn{flex:1}
}

</style></head><body><!--SHELL_HEADER--><main class="wrap"><header class="pagehead"><div class="pagehead-text"><div class="eyebrow">[[i18n:repurpose.eyebrow]]</div><h1>[[i18n:repurpose.title]]</h1><p class="muted">[[i18n:repurpose.intro]]</p></div><div class="head-actions"><button type="button" class="btn primary" id="new-plan">[[i18n:repurpose.newPlan]]</button><button type="button" class="btn" id="refresh-inbox">[[i18n:common.refresh]]</button></div></header><div class="repurpose-layout"><aside class="plan-inbox" aria-label="[[i18n:repurpose.planList]]"><div class="tabs"><button type="button" class="is-active" data-filter="draft">[[i18n:repurpose.status.pending]]</button><button type="button" data-filter="approved">[[i18n:repurpose.status.approved]]</button><button type="button" data-filter="all">[[i18n:common.all]]</button></div><ol class="plan-list" id="plan-list"><li class="loading">[[i18n:common.loading]]</li></ol></aside><section class="plan-workspace"><div class="empty" id="workspace-empty"><b>[[i18n:repurpose.workspaceEmpty]]</b><span>[[i18n:repurpose.workspaceEmptyWhy]]</span><button type="button" class="btn btn--primary" data-open-new-plan>[[i18n:repurpose.newPlan]]</button></div><div id="workspace" hidden><div class="plan-titlebar"><div><div class="plan-title-row"><h2 id="plan-title"></h2><span id="plan-status" class="pill"></span></div><div class="muted" id="plan-meta"></div><div class="plan-id-row"><code id="plan-id"></code><button type="button" class="btn quiet" id="copy-id">[[i18n:repurpose.copyId]]</button></div></div><div class="plan-titlebar-actions"><button type="button" class="btn" id="revision-history">[[i18n:repurpose.revisionHistory]]</button></div></div><div class="callout" id="history-banner" hidden>[[i18n:repurpose.historyBanner]]</div><div id="result" class="plan" aria-live="polite"></div><div class="plan-command-bar"><span class="status" id="statusline"></span><div class="cmd-actions"><button type="button" class="btn primary" id="save-rev">[[i18n:repurpose.saveRevision]]</button><button type="button" class="btn approve" id="approve">[[i18n:repurpose.approveThis]]</button></div></div></div></section></div></main>
<dialog id="new-plan-dialog" class="ui-dialog"><button type="button" class="dialog-close" data-close="new-plan-dialog" aria-label="[[i18n:common.close]]">×</button><h3>[[i18n:repurpose.newPlanDialogTitle]]</h3><form id="plan-form" onsubmit="createPlan(event)"><div class="field"><label for="brief">[[i18n:repurpose.briefLabel]]</label><textarea id="brief" required placeholder="[[i18n:repurpose.briefPlaceholder]]"></textarea></div><div class="row"><div class="field"><label for="duration">[[i18n:repurpose.durationLabel]]</label><input id="duration" type="number" min="5" value="30"></div><div class="field"><label for="style">[[i18n:repurpose.styleLabel]]</label><input id="style" placeholder="[[i18n:repurpose.stylePlaceholder]]"></div><div class="field"><label for="audience">[[i18n:repurpose.audienceLabel]]</label><input id="audience" placeholder="[[i18n:repurpose.audiencePlaceholder]]"></div></div><div class="error" id="error"></div><div class="dialog-actions"><button type="button" class="btn" data-close="new-plan-dialog">[[i18n:common.cancel]]</button><button type="submit" class="btn primary" id="create">[[i18n:repurpose.generatePlan]]</button></div></form></dialog>
<dialog id="plan-shot-dialog" class="ui-dialog ui-dialog--media"><button type="button" class="dialog-close" data-close="plan-shot-dialog" aria-label="[[i18n:common.close]]">×</button><h3 id="shot-title"></h3><video id="shot-video" class="shot-video" controls preload="metadata"></video><div class="shot-dialog-meta"><div><b>[[i18n:repurpose.shot.asset]]</b><br><span id="shot-asset"></span></div><div><b>[[i18n:repurpose.shot.time]]</b><br><span id="shot-time"></span></div><div><b>[[i18n:repurpose.shot.duration]]</b><br><span id="shot-duration"></span></div><div><b>[[i18n:repurpose.shot.match]]</b><br><span id="shot-score"></span></div></div><div class="dialog-actions"><button type="button" class="btn primary" data-close="plan-shot-dialog">[[i18n:common.close]]</button></div></dialog>
<dialog id="revision-dialog" class="ui-dialog"><button type="button" class="dialog-close" data-close="revision-dialog" aria-label="[[i18n:common.close]]">×</button><h3>[[i18n:repurpose.revisionHistory]]</h3><ol class="revision-list" id="revision-list"></ol></dialog><script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fmt=ms=>{ms=Math.max(0,Math.floor((ms||0)/1000));return String(Math.floor(ms/60)).padStart(2,'0')+':'+String(ms%60).padStart(2,'0')};const fmtDateTime=v=>{if(!v)return '';const d=new Date(v);return isNaN(d.getTime())?'':tdFormatDateTime(d)};
const roleKeys={opening:'repurpose.role.opening',hook:'repurpose.role.hook',body:'repurpose.role.body',ending:'repurpose.role.ending',transition:'repurpose.role.transition',broll:'repurpose.role.broll',cta:'repurpose.role.cta'};const roleName=role=>tdT(roleKeys[role]||role);
const state={plans:[],filter:'draft',active:null,revision:null,revisions:[],dirty:false};
function csrfToken(){const prefix='__Host-nexusslate_csrf=';const item=document.cookie.split('; ').find(function(x){return x.indexOf(prefix)===0});return item?decodeURIComponent(item.slice(prefix.length)):''}
function authHeaders(base){const headers=new Headers(base||{});const csrf=csrfToken();if(csrf)headers.set('X-CSRF-Token',csrf);return headers}
async function api(url,opt){opt=opt||{};const r=await fetch(url,{...opt,headers:authHeaders(opt.headers)});if(!r.ok){if(r.status===401)throw Error(tdT('common.loginRequiredTop'));throw Error(await tdApiErrorMessage(r))}return r.json()}
function status(text){const el=document.getElementById('statusline');if(el)el.textContent=text}
function setDirty(v){state.dirty=v;const btn=document.getElementById('save-rev');if(btn)btn.disabled=!v}
window.addEventListener('beforeunload',function(e){if(state.dirty){e.preventDefault();e.returnValue=''}});
function confirmDiscard(){if(!state.dirty)return true;return confirm(tdT('repurpose.confirmDiscard'))}
async function downloadExport(kind){if(!state.active)return;try{const r=await fetch('/api/v1/repurpose/plans/'+encodeURIComponent(state.active.id)+'/export.'+kind,{headers:authHeaders()});if(!r.ok){if(r.status===401)throw Error(tdT('common.loginRequiredTop'));throw Error(await tdApiErrorMessage(r))}const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=state.active.id+'.'+kind;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}catch(e){alert(tdT('repurpose.exportError',{message:e.message}))}}
// --- inbox ------------------------------------------------------------
async function loadInbox(){let items;try{items=await api('/api/v1/repurpose/plans?status='+encodeURIComponent(state.filter)+'&limit=50')}catch(e){document.getElementById('plan-list').innerHTML='<li class="empty">'+esc(tdT('repurpose.loadInboxError',{message:e.message}))+'</li>';return}state.plans=Array.isArray(items)?items:[];renderInbox()}
function renderInbox(){const list=document.getElementById('plan-list');if(!state.plans.length){list.innerHTML='<li class="empty"><b>'+esc(tdT(state.filter==='approved'?'repurpose.inboxEmptyApproved':'repurpose.inboxEmpty'))+'</b><span>'+esc(tdT('repurpose.inboxEmptyWhy'))+'</span><button type="button" class="btn btn--primary" data-open-new-plan>'+esc(tdT('repurpose.newPlan'))+'</button></li>';return}list.innerHTML=state.plans.map(function(p){const active=state.active&&p.id===state.active.id;return '<li><button type="button" class="plan-row"'+(active?' aria-current="true"':'')+' data-plan="'+esc(p.id)+'"><div class="pl-title">'+esc(p.title||tdT('repurpose.untitled'))+' <span class="state '+(p.status==='approved'?'state--confirmed':'state--draft')+'">'+esc(tdT(p.status==='approved'?'repurpose.status.approved':'repurpose.status.pending'))+'</span></div><div class="pl-meta"><span>'+fmt(p.duration_ms)+'</span><span>v'+(p.latest_revision||0)+'</span>'+(p.missing_needs_count>0?'<span>'+esc(tdPlural('repurpose.missingNeeds',p.missing_needs_count||0))+'</span>':'')+'<span>'+fmtDateTime(p.updated_at)+'</span></div></button></li>'}).join('')}
document.getElementById('plan-list').addEventListener('click',function(e){const np=e.target.closest('[data-open-new-plan]');if(np){openNewPlanDialog();return}const b=e.target.closest('[data-plan]');if(b)openPlan(b.dataset.plan)});
document.querySelectorAll('.tabs button').forEach(function(f){f.addEventListener('click',function(){document.querySelectorAll('.tabs button').forEach(function(x){x.classList.remove('is-active')});f.classList.add('is-active');state.filter=f.dataset.filter;loadInbox()})});
document.getElementById('refresh-inbox').addEventListener('click',loadInbox);
// --- workspace ---------------------------------------------------------
async function openPlan(id){if(!confirmDiscard())return;try{const [plan,revisions]=await Promise.all([api('/api/v1/repurpose/plans/'+encodeURIComponent(id)),api('/api/v1/repurpose/plans/'+encodeURIComponent(id)+'/revisions')]);state.active=plan;state.revisions=Array.isArray(revisions)?revisions:[];state.revision=null;state.dirty=false;renderPlan(plan,null);const url=new URL(location.href);url.searchParams.set('plan',id);url.searchParams.delete('revision');history.replaceState(null,'',url);loadInbox();document.getElementById('workspace-empty').hidden=true;document.getElementById('workspace').hidden=false}catch(e){alert(tdT('repurpose.openError',{message:e.message}))}}
function revisionPlan(revision){const p=revision.plan||{};state.active=p;state.revision=revision.revision;state.dirty=false;renderPlan(p,revision.revision);const url=new URL(location.href);url.searchParams.set('plan',p.id);url.searchParams.set('revision',String(revision.revision));history.replaceState(null,'',url)}
function renderPlan(plan,viewRevision){state.active=plan;const latest=state.revisions.length?state.revisions[0].revision:0;const viewOnly=viewRevision!=null&&viewRevision!==latest;document.getElementById('plan-title').textContent=plan.title||tdT('repurpose.untitled');const st=document.getElementById('plan-status');st.textContent=tdT(plan.status==='approved'?'repurpose.status.approved':'repurpose.status.pending');st.className='state '+(plan.status==='approved'?'state--confirmed':'state--draft');document.getElementById('plan-meta').textContent=tdT('repurpose.planMetaTarget',{duration:fmt(plan.duration_ms)})+(plan.style?' · '+plan.style:'')+(plan.audience?' · '+plan.audience:'')+(plan.provider?' · '+plan.provider:'')+tdT('repurpose.planMetaUpdated',{time:fmtDateTime(plan.updated_at)});document.getElementById('plan-id').textContent=plan.id;document.getElementById('history-banner').hidden=!viewOnly;const sections=(plan.sections||[]).map(function(s){return renderSection(s,viewOnly)}).join('');document.getElementById('result').innerHTML=sections||'<div class="muted">'+esc(tdT('repurpose.noSections'))+'</div>';const saveBtn=document.getElementById('save-rev');const approveBtn=document.getElementById('approve');saveBtn.disabled=!state.dirty||viewOnly||plan.status==='approved';approveBtn.disabled=viewOnly||plan.status==='approved'||(state.revisions[0]?state.revisions[0].state!=='draft':false);setDirty(false);status(viewOnly?tdT('repurpose.historyStatus',{revision:viewRevision}):'')}
function renderSection(s,viewOnly){const cards=(s.candidates||[]).slice().sort(function(a,b){return (a.shot_id===s.selected_shot_id?-1:0)-(b.shot_id===s.selected_shot_id?-1:0)}).map(function(c){return candidate(s,c,viewOnly)}).join('');const reqPill='<span class="pill">'+esc(tdT(s.required?'repurpose.section.required':'repurpose.section.optional'))+'</span>';const lockPill=s.locked?' <span class="pill">'+esc(tdT('repurpose.section.locked'))+'</span>':'';const secActions=viewOnly?reqPill+lockPill:reqPill+lockPill+'<div class="cand-actions"><button type="button" class="btn" data-action="'+(s.locked?'unlock':'lock')+'" data-role="'+esc(s.role)+'">'+esc(tdT(s.locked?'repurpose.section.unlock':'repurpose.section.lock'))+'</button><button type="button" class="btn quiet" data-action="alternatives" data-role="'+esc(s.role)+'">'+esc(tdT('repurpose.section.alternatives'))+'</button></div>';return '<section class="section"><div class="sectionhead"><div><div class="role">'+esc(roleName(s.role))+'</div><div class="small">'+esc(tdT('repurpose.section.meta',{duration:fmt(s.duration_ms),query:s.query}))+'</div></div><div class="sectionactions">'+secActions+'</div></div><div class="rationale">'+esc(s.rationale||'')+'</div><div class="candidates">'+cards+'</div></section>'}
function candidate(s,c,viewOnly){const selected=s.selected_shot_id===c.shot_id,excluded=(s.excluded_shot_ids||[]).includes(c.shot_id),image='/api/v1/assets/'+encodeURIComponent(c.asset_id)+'/thumbnail',why=(c.reasons||[]).map(esc).join(' · ')||tdT('repurpose.candidate.sortedByRelevance');const actions=viewOnly?'':'<div class="cand-actions"><button type="button" class="btn" data-action="preview" data-asset="'+esc(c.asset_id)+'" data-start="'+c.start_ms+'" data-end="'+c.end_ms+'">'+esc(tdT('repurpose.candidate.preview',{start:fmt(c.start_ms),end:fmt(c.end_ms)}))+'</button><button type="button" class="btn" data-action="choose" data-role="'+esc(s.role)+'" data-shot="'+esc(c.shot_id)+'"'+(selected||s.locked?' disabled':'')+'>'+esc(tdT('repurpose.candidate.choose'))+'</button><button type="button" class="btn quiet" data-action="exclude" data-role="'+esc(s.role)+'" data-shot="'+esc(c.shot_id)+'">'+esc(tdT(excluded?'repurpose.candidate.unexclude':'repurpose.candidate.exclude'))+'</button></div>';return '<article class="panel candidate-card '+(selected?'selected ':'')+(excluded?'excluded':'')+'"><img class="thumb" loading="lazy" src="'+image+'" onerror="this.style.visibility=\'hidden\'" alt="'+esc(tdT('repurpose.candidate.thumbAlt'))+'"><div class="cand-body"><b>'+fmt(c.start_ms)+' — '+fmt(c.end_ms)+'</b> <span class="pill">'+esc(tdT('repurpose.candidate.matchScore',{percent:Math.round(Number(c.score||0)*100)}))+'</span>'+(c.reused?' <span class="pill">'+esc(tdT('repurpose.candidate.reused'))+'</span>':'')+(selected?' <span class="state state--confirmed">'+esc(tdT('repurpose.candidate.selected'))+'</span>':'')+(excluded?' <span class="pill">'+esc(tdT('repurpose.candidate.excluded'))+'</span>':'')+'<div class="small">'+esc(tdT('repurpose.candidate.assetShot',{asset:c.asset_id,shot:c.shot_id}))+'</div><div class="small">'+why+'</div>'+actions+'</div></article>'}
document.getElementById('result').addEventListener('click',function(e){const b=e.target.closest('[data-action]');if(!b)return;const act=b.dataset.action;if(act==='preview'){openShotDialog(b.dataset.asset,Number(b.dataset.start),Number(b.dataset.end));return}const role=b.dataset.role;if(act==='choose')choose(role,b.dataset.shot);else if(act==='exclude')toggleExclude(role,b.dataset.shot);else if(act==='lock')lock(role);else if(act==='unlock')unlock(role);else if(act==='alternatives')findAlternatives(role)});
function section(role){return (state.active.sections||[]).find(function(s){return s.role===role})}
function choose(role,shot){const s=section(role);if(!s)return;if(s.locked){alert(tdT('repurpose.choose.locked'));return}s.selected_shot_id=shot;s.excluded_shot_ids=(s.excluded_shot_ids||[]).filter(id=>id!==shot);rerender()}
function toggleExclude(role,shot){const s=section(role);if(!s)return;if(s.selected_shot_id===shot){alert(tdT('repurpose.exclude.selected'));return}const ids=s.excluded_shot_ids||[];s.excluded_shot_ids=ids.includes(shot)?ids.filter(id=>id!==shot):ids.concat(shot);rerender()}
function rerender(){renderPlan(state.active,state.revision);setDirty(true);status(tdT('repurpose.dirtyStatus'))}
async function findAlternatives(role){const s=section(role);if(!s)return;try{const hits=await api('/api/v1/search/shots/hybrid?q='+encodeURIComponent(s.query)+'&limit=12');let added=0;(hits||[]).forEach(h=>{if((s.candidates||[]).some(c=>c.shot_id===h.id))return;(s.candidates=s.candidates||[]).push({shot_id:h.id,asset_id:h.asset_id,start_ms:h.start_ms,end_ms:h.end_ms,score:h.score||0,reasons:[h.description||'',...(h.tags||[])].filter(Boolean)});added++});if(!added)alert(tdT('repurpose.alternatives.none'));rerender()}catch(e){alert(tdT('repurpose.alternatives.error',{message:e.message}))}}
async function saveRevision(){if(!state.active||!state.dirty||state.revision)return;try{const r=await api('/api/v1/repurpose/plans/'+state.active.id+'/revisions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sections:state.active.sections,editor_note:document.getElementById('editor-note')?document.getElementById('editor-note').value:''})});state.active=r.plan;state.revision=null;state.dirty=false;state.revisions=await api('/api/v1/repurpose/plans/'+state.active.id+'/revisions');renderPlan(state.active,null);status(tdT('repurpose.savedRevision',{revision:r.revision}));loadInbox()}catch(e){alert(tdT('repurpose.saveError',{message:e.message}))}}
async function createPlan(e){e.preventDefault();const b=document.getElementById('create'),error=document.getElementById('error');if(b)b.disabled=true;if(error)error.textContent='';try{const p=await api('/api/v1/repurpose/plans',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({brief:document.getElementById('brief').value,duration_ms:Number(document.getElementById('duration').value)*1000,style:document.getElementById('style').value,audience:document.getElementById('audience').value})});closeDialog('new-plan-dialog');openPlan(p.id)}catch(err){if(error)error.textContent=tdT('repurpose.createError',{message:err.message})}finally{if(b)b.disabled=false}}
async function approve(){if(!state.active)return;if(state.dirty){alert(tdT('repurpose.approve.saveFirst'));return}if(!confirm(tdT('repurpose.approve.confirm')))return;try{const revisions=state.revisions.length?state.revisions:await api('/api/v1/repurpose/plans/'+state.active.id+'/revisions');const latest=revisions[0];const approved=await api('/api/v1/repurpose/plans/'+state.active.id+'/revisions/'+latest.revision+'/approve',{method:'POST'});state.active=approved.plan;state.revision=null;state.dirty=false;renderPlan(approved.plan,null);status(tdT('repurpose.approve.done'));loadInbox()}catch(e){alert(tdT('repurpose.approve.error',{message:e.message}))}}
document.getElementById('save-rev').addEventListener('click',saveRevision);
document.getElementById('approve').addEventListener('click',approve);
document.getElementById('copy-id').addEventListener('click',function(){navigator.clipboard.writeText(state.active.id).then(function(){const b=document.getElementById('copy-id');b.textContent=tdT('common.copied');setTimeout(function(){b.textContent=tdT('repurpose.copyId')},1500)}).catch(function(){prompt(tdT('repurpose.copyPlanId'),state.active.id)})});
// --- dialogs -----------------------------------------------------------
function openDialog(id,opener,focus){tdOpenSurface(id,opener,focus)}
function closeDialog(id){const d=document.getElementById(id);if(!d)return;tdCloseSurface(id);const v=document.getElementById('shot-video');if(id==='plan-shot-dialog'&&v){v.pause();v.removeAttribute('src');v.load()}}
document.querySelectorAll('[data-close]').forEach(function(b){b.addEventListener('click',function(){closeDialog(b.dataset.close)})});
function openNewPlanDialog(){openDialog('new-plan-dialog',document.getElementById('new-plan'),'#brief')}
document.getElementById('new-plan').addEventListener('click',openNewPlanDialog);
document.getElementById('workspace-empty').addEventListener('click',function(e){if(e.target.closest('[data-open-new-plan]'))openNewPlanDialog()});
document.getElementById('revision-history').addEventListener('click',function(){renderRevisionList();openDialog('revision-dialog',document.getElementById('revision-history'))});
function renderRevisionList(){const list=document.getElementById('revision-list');if(!state.revisions.length){list.innerHTML='<li class="empty">'+esc(tdT('repurpose.revisions.empty'))+'</li>';return}list.innerHTML=state.revisions.map(function(r){const current=state.revision===r.revision;return '<li><button type="button" class="revision-row"'+(current?' aria-current="true"':'')+' data-revision="'+r.revision+'"><b>v'+r.revision+'</b> <span class="state '+(r.state==='approved'?'state--confirmed':'state--draft')+'">'+esc(tdT(r.state==='approved'?'repurpose.status.approved':'repurpose.revision.draft'))+'</span><div class="rv-meta">'+fmtDateTime(r.created_at)+'</div>'+(r.editor_note?'<div class="rv-note">'+esc(r.editor_note)+'</div>':'')+'</button></li>'}).join('')}
document.getElementById('revision-list').addEventListener('click',function(e){const b=e.target.closest('[data-revision]');if(b){if(state.dirty&&!confirmDiscard())return;const r=state.revisions.find(x=>x.revision===Number(b.dataset.revision));if(r)revisionPlan(r);closeDialog('revision-dialog')}});
function openShotDialog(assetID,startMS,endMS){const v=document.getElementById('shot-video');document.getElementById('shot-title').textContent=fmt(startMS)+' – '+fmt(endMS);document.getElementById('shot-asset').textContent=assetID;document.getElementById('shot-time').textContent=fmt(startMS)+' – '+fmt(endMS);document.getElementById('shot-duration').textContent=fmt(endMS-startMS);document.getElementById('shot-score').textContent=tdT('repurpose.shot.previewLabel');v.src='/api/v1/assets/'+encodeURIComponent(assetID)+'/proxy#t='+Math.floor(startMS/1000)+','+Math.floor(endMS/1000);openDialog('plan-shot-dialog',null,null);v.onloadedmetadata=function(){try{v.currentTime=startMS/1000}catch(_){}};v.ontimeupdate=function(){if(v.currentTime>=(endMS-startMS)/1000+startMS/1000){}}}
// --- boot --------------------------------------------------------------
const params=new URLSearchParams(location.search);const bootPlan=params.get('plan');const bootRevision=params.get('revision');
(async function init(){await loadInbox();if(bootPlan){try{const [plan,revisions]=await Promise.all([api('/api/v1/repurpose/plans/'+encodeURIComponent(bootPlan)),api('/api/v1/repurpose/plans/'+encodeURIComponent(bootPlan)+'/revisions')]);state.active=plan;state.revisions=Array.isArray(revisions)?revisions:[];if(bootRevision){const r=state.revisions.find(x=>x.revision===Number(bootRevision));if(r){state.revision=r.revision;renderPlan(r.plan,r.revision)}else{state.revision=null;renderPlan(plan,null)}}else{state.revision=null;renderPlan(plan,null)}document.getElementById('workspace-empty').hidden=true;document.getElementById('workspace').hidden=false}catch(e){}}else{const draft=state.plans.find(p=>p.status==='draft');if(draft)openPlan(draft.id)}})().catch(function(){});
setInterval(loadInbox,20000);
</script></body></html>`
