package api

const setupHTML = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Timingdex · 启动配置</title>
<style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#101827;color:#edf3ff;font:15px system-ui,sans-serif}header{padding:15px 6vw;border-bottom:1px solid #263651;display:flex;gap:18px;align-items:center}a{color:#b8c8ff;text-decoration:none}.brand{font-weight:850;color:#fff;margin-right:auto}.wrap{max-width:920px;margin:auto;padding:46px 24px}h1{font-size:44px;letter-spacing:-.05em;margin:8px 0}.muted{color:#aab8d0;line-height:1.65}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:26px}.panel{background:#172238;border:1px solid #2c3d5b;border-radius:15px;padding:20px}.step{display:flex;gap:12px;padding:13px 0;border-bottom:1px solid #2a3a54}.step:last-child{border:0}.num{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:#8da7ff;color:#081225;font-weight:900}.button{display:inline-block;margin-top:12px;padding:10px 14px;border-radius:9px;background:#8da7ff;color:#081225;font-weight:850}.status{margin-top:12px;padding:12px;border-radius:9px;background:#0d1728}.ok{color:#82e4ad}.bad{color:#ff9cab}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style></head>
<body><header><span class="brand">Timingdex</span><a href="/">素材库</a><a href="/providers">模型通道</a><a href="/progress">处理进度</a><a href="/library-roots">添加素材目录</a></header>
<main class="wrap"><div class="muted">LOCAL-FIRST SETUP</div><h1>三步启动素材库</h1><p class="muted">Hub 管理素材、密钥和工作流；模型 Key 在「模型通道」中一次录入，保存到受保护的 Hub 密钥库。</p>
<div class="grid"><section class="panel"><div class="step"><span class="num">1</span><div><b>启动 Hub</b><div class="muted">运行 timingdex serve，并保存首次生成的管理 Token。</div></div></div><div class="step"><span class="num">2</span><div><b>配置模型通道</b><div class="muted">按视频理解、ASR、Embedding 等能力添加 Provider；同一 Provider 可添加多个 Key。</div><a class="button" href="/providers">打开模型通道</a></div></div><div class="step"><span class="num">3</span><div><b>添加素材目录</b><div class="muted">添加本机目录，或者贴上 NAS / SMB 共享地址，让向导给出挂载命令、验证挂载，再添加并开始扫描。</div><a class="button" href="/library-roots">打开素材目录向导</a></div></div></section>
<aside class="panel"><h2>运行状态</h2><div id="health" class="status">正在检查 Hub…</div><p class="muted">页面不会生成含 API Key 的终端命令，也不会把凭据写入浏览器存储。</p></aside></div></main>
<script>async function check(){const el=document.getElementById('health');try{const h=await fetch('/api/v1/health').then(r=>r.json());el.className='status ok';el.textContent='Hub 已运行 · '+h.status}catch(e){el.className='status bad';el.textContent='尚未连接 Hub，请先运行 timingdex serve'}}check()</script>
</body></html>`
