package api

// tagsHTML is the /tags curator.
const tagsHTML = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NexusGate · [[i18n:tags.title]]</title><style>

.head-actions{display:flex;gap:10px}
.summary{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:16px}
#tags-status:empty{display:none}
.panel{padding:16px;margin-bottom:16px}
.panel h2{margin:0 0 12px}
details{margin-top:12px}
details summary{cursor:pointer;color:var(--text-muted);font-size:14px}
details input{width:90px}
@media(max-width:700px){
}

</style></head><body><!--SHELL_HEADER--><main class="wrap"><header class="pagehead"><div><div class="eyebrow">[[i18n:tags.title]]</div><h1>[[i18n:tags.title]]</h1><p class="muted">[[i18n:tags.subtitle]]</p></div><div class="head-actions"><button type="button" class="btn btn--primary" id="curate-btn">[[i18n:tags.curate]]</button><button type="button" class="btn" id="refresh-tags">[[i18n:common.refresh]]</button></div></header><div class="summary"><span class="state state--attention">[[i18n:tags.unresolvedCount]] <b id="count-unresolved">–</b></span><span class="state state--draft">[[i18n:tags.proposalsHeading]] <b id="count-proposals">–</b></span><span class="state state--confirmed">[[i18n:tags.canonicalHeading]] <b id="count-canonical">–</b></span></div><div class="callout" id="tags-status"></div><details><summary>[[i18n:tags.clusterAdvanced]]</summary><div style="margin-top:8px;display:flex;gap:8px;align-items:center"><label for="cluster-threshold">[[i18n:tags.clusterThreshold]]</label><input id="cluster-threshold" type="number" step="0.01" min="0" max="1" value="0.86"><button type="button" class="btn" id="cluster-btn">[[i18n:tags.cluster]]</button></div></details><section class="panel"><h2>[[i18n:tags.proposalsHeading]]</h2><div id="proposals"><p class="muted">[[i18n:common.loading]]</p></div></section><section class="panel"><h2>[[i18n:tags.unresolvedHeading]]</h2><div id="unresolved"><p class="muted">[[i18n:common.loading]]</p></div></section><section class="panel"><h2>[[i18n:tags.canonicalHeading]]</h2><div id="tags"><p class="muted">[[i18n:common.loading]]</p></div></section></main>
<script>
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
 function csrfToken(){const prefix='__Host-nexusgate_csrf=';const item=document.cookie.split('; ').find(function(x){return x.indexOf(prefix)===0});return item?decodeURIComponent(item.slice(prefix.length)):''}
 function authHeaders(base){const headers=new Headers(base||{});const csrf=csrfToken();if(csrf)headers.set('X-CSRF-Token',csrf);return headers}
async function j(url,opt){opt=opt||{};const r=await fetch(url,{...opt,headers:authHeaders(opt.headers)});if(!r.ok){if(r.status===401)throw new Error(tdT('common.loginRequiredTop'));throw new Error(await tdApiErrorMessage(r))}return r.json()}
 function unresolvedTable(xs){return '<div class="table-scroll"><table class="table"><tr><th>'+esc(tdT('tags.thNormalized'))+'</th><th>'+esc(tdT('tags.thOriginal'))+'</th><th>'+esc(tdT('tags.thAssetCount'))+'</th></tr>'+xs.map(x=>'<tr><td>'+esc(x.normalized_tag)+'</td><td>'+x.display_forms.map(v=>'<span class="pill">'+esc(v)+'</span>').join('')+'</td><td>'+numeric(x.asset_count)+'</td></tr>').join('')+'</table></div>'}
 function proposalTable(xs){return '<div class="table-scroll"><table class="table"><tr><th>'+esc(tdT('tags.thAction'))+'</th><th>'+esc(tdT('tags.thCanonical'))+'</th><th>'+esc(tdT('tags.thReason'))+'</th><th>'+esc(tdT('tags.thImpact'))+'</th><th></th></tr>'+xs.map(x=>'<tr><td>'+esc(x.proposal_type)+'</td><td>'+esc(x.canonical_name)+'</td><td>'+esc(x.reason)+'<div class="muted">'+esc(tdT('tags.confidence',{pct:Math.round(Number(x.confidence||0)*100)}))+'</div></td><td>'+numeric(x.affected_assets)+'</td><td><button class="approve" data-action="review" data-id="'+esc(x.id)+'" data-review="approve">'+esc(tdT('tags.approve'))+'</button> <button class="reject" data-action="review" data-id="'+esc(x.id)+'" data-review="reject">'+esc(tdT('tags.reject'))+'</button></td></tr>').join('')+'</table></div>'}
 function numeric(v){const n=Number(v);return Number.isFinite(n)?tdFormatNumber(n):'0'}
 function tagTable(xs){return '<div class="table-scroll"><table class="table"><tr><th>'+esc(tdT('tags.thCanonical'))+'</th><th>'+esc(tdT('tags.thCategory'))+'</th><th>'+esc(tdT('tags.thAssets'))+'</th><th>'+esc(tdT('tags.thAliases'))+'</th></tr>'+xs.map(x=>'<tr><td>'+esc(x.canonical_name)+'</td><td>'+esc(x.category)+'</td><td>'+numeric(x.usage_count)+'</td><td>'+numeric(x.alias_count)+'</td></tr>').join('')+'</table></div>'}
function emptyBlock(titleKey,whyKey){return '<div class="empty"><span class="label">'+esc(tdT(titleKey))+'</span><div class="muted">'+esc(tdT(whyKey))+'</div><button type="button" class="btn btn--primary" onclick="curate()">'+esc(tdT('tags.curate'))+'</button></div>'}
function tagStatus(msg,ok){const el=document.getElementById('tags-status');if(!el)return;el.textContent=msg;el.className='callout '+(ok===false?'callout--contradicted':(ok?'callout--confirmed':''))}
async function safeLoad(){try{const [u,p,t]=await Promise.all([j('/api/v1/tags/unresolved'),j('/api/v1/tags/proposals?state=pending'),j('/api/v1/tags')]);document.getElementById('unresolved').innerHTML=(u&&u.length)?unresolvedTable(u):emptyBlock('tags.emptyUnresolved','tags.emptyUnresolvedWhy');document.getElementById('proposals').innerHTML=(p&&p.length)?proposalTable(p):emptyBlock('tags.emptyProposals','tags.emptyProposalsWhy');document.getElementById('tags').innerHTML=(t&&t.length)?tagTable(t):emptyBlock('tags.emptyCanonical','tags.emptyCanonicalWhy');document.getElementById('count-unresolved').textContent=tdFormatNumber((u||[]).length);document.getElementById('count-proposals').textContent=tdFormatNumber((p||[]).length);document.getElementById('count-canonical').textContent=tdFormatNumber((t||[]).length);tagStatus('')}catch(e){tagStatus(tdT('tags.loadError',{msg:e.message}),false)}}
async function curate(){const b=document.getElementById('curate-btn');if(b)b.disabled=true;tagStatus(tdT('tags.curateRunning'));try{const r=await j('/api/v1/tags/curate',{method:'POST'});const scanned=r&&(r.scanned||r.total||0),created=r&&(r.proposals||r.created||0);tagStatus(tdT('tags.curateDone',{scanned:scanned,created:created}),true);await safeLoad()}catch(e){tagStatus(tdT('tags.curateError',{msg:e.message}),false)}finally{if(b)b.disabled=false}}
async function cluster(){const b=document.getElementById('cluster-btn');if(b)b.disabled=true;tagStatus(tdT('tags.clusterRunning'));try{const th=document.getElementById('cluster-threshold').value||'0.86';const r=await j('/api/v1/tags/clusters?threshold='+encodeURIComponent(th),{method:'POST'});const n=r&&(r.proposals||r.created||0);tagStatus(tdT('tags.clusterDone',{count:n}),true);await safeLoad()}catch(e){tagStatus(tdT('tags.clusterError',{msg:e.message}),false)}finally{if(b)b.disabled=false}}
async function review(id,action){try{const r=await j('/api/v1/tags/proposals/'+id+'/review',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action})});tagStatus(action==='approve'?tdT('tags.approvedDone'):tdT('tags.rejectedDone'),true);await safeLoad()}catch(e){tagStatus(tdT('tags.reviewError',{msg:e.message}),false)}}
document.getElementById('curate-btn').addEventListener('click',curate);
document.getElementById('cluster-btn').addEventListener('click',cluster);
safeLoad();
document.getElementById('refresh-tags').addEventListener('click',safeLoad);
</script></body></html>`
