package api

import "net/http"

func (s *Server) workersPage(w http.ResponseWriter, r *http.Request) {
	s.serveLocalizedPage(w, r, "/workers", workersPageHTML)
}

const workersPageHTML = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Timingdex · [[i18n:workers.title]]</title><style>

.head-actions{display:flex;gap:10px}
.fleet-summary{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:16px}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}
.panel h2{margin:0 0 12px}

.worker-list,.job-list{display:block}
.worker-card,.job-card{padding:14px}
.worker-card .node-head,.job-card .job-head{display:flex;gap:10px;justify-content:space-between;align-items:center;flex-wrap:wrap}
.worker-card .name,.job-card .name{font-weight:800}
.worker-card .meta,.job-card .meta{color:var(--text-muted);font-size:13px;margin-top:6px;line-height:1.7}
.failure{color:var(--ev-contradicted)}
.bar{height:6px;background:var(--inset);border-radius:3px;margin-top:5px;overflow:hidden}
.bar i{display:block;height:100%;background:var(--rule-strong)}
.assign{display:flex;gap:8px;margin-top:10px;flex-wrap:wrap}
.assign select{flex:1;min-width:120px}
.assign .btn{padding:8px 12px;font-size:13px}
.token{background:var(--inset);border:1px solid var(--rule);border-radius:10px;padding:10px 12px;margin-top:10px;font-family:var(--font-data);font-size:13px;word-break:break-all;color:var(--text-muted)}
.details-wrap{margin-top:16px}
.details-wrap details{background:var(--raised);border:1px solid var(--rule);border-radius:12px;padding:12px 14px}
.details-wrap summary{cursor:pointer;color:var(--text-muted);font-size:14px}
.details-wrap .token-actions{display:flex;gap:8px;align-items:center;margin-top:10px;flex-wrap:wrap}
.notice{color:var(--text-muted);font-size:12px;margin-top:8px}
.status{color:var(--ev-confirmed);font-size:13px;margin-top:8px}
@media(max-width:760px){.grid{grid-template-columns:1fr}
}

</style></head><body data-workers-page><!--SHELL_HEADER--><main class="wrap"><header class="pagehead"><div><div class="eyebrow">[[i18n:workers.title]]</div><h1>[[i18n:workers.title]]</h1><p class="muted">[[i18n:workers.subtitle]]</p></div><div class="head-actions"><a class="btn btn--primary" id="add-worker-btn" href="/worker-setup">[[i18n:workers.addWorker]]</a><button type="button" class="btn" id="refresh">[[i18n:common.refresh]]</button></div></header><div class="callout callout--attention" id="auth-callout" hidden><span>[[i18n:workers.authRequired]]</span><button type="button" class="btn" id="login-prompt">[[i18n:workers.loginToView]]</button></div><div class="callout callout--attention" id="admin-auth-callout" hidden><span>[[i18n:workers.adminAuthWarning]]</span></div><div class="fleet-summary" id="fleet-summary" hidden></div><div class="grid"><section class="panel"><h2>[[i18n:workers.title]]</h2><div id="workers" class="worker-list">[[i18n:workers.loading]]</div></section><section class="panel"><h2>[[i18n:workers.jobsTitle]]</h2><div id="jobs" class="job-list">[[i18n:workers.loading]]</div></section></div><div class="details-wrap"><details id="advanced-pairing"><summary>[[i18n:workers.advancedPairing]]</summary><p class="notice">[[i18n:workers.advancedPairingNoteLead]] <a href="/worker-setup">[[i18n:workers.installWizard]]</a>[[i18n:workers.advancedPairingNoteTrail]]</p><button type="button" class="btn" id="pairing-btn">[[i18n:workers.generatePairingToken]]</button><div id="pairing" class="token" hidden></div></details></div></main>
<script>
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function node(w){const c=w.capabilities||{},online=w.status==='online',compat=w.compat||{};const caps=[c.proxy?tdT('workers.cap.preview'):'',c.thumbnail?tdT('workers.cap.thumbnail'):'',c.audio_extract?tdT('workers.cap.audio'):''].filter(Boolean).join(' · ')||tdT('workers.cap.none');const roots=(c.library_roots||[]).join(tdT('workers.listSeparator'))||tdT('workers.rootsNone');const hardware=(c.hardware||[]).join(tdT('workers.listSeparator'))||tdT('workers.hardwareSoftware');const vmap={compatible:['workers.compat.compatible','compat-ok'],upgrade_recommended:['workers.compat.upgradeRecommended','compat-warn'],incompatible:['workers.compat.incompatible','compat-bad']};const vp=vmap[compat.verdict]||['workers.compat.unknown','compat-warn'];const vline='<br>'+esc(tdT('workers.versionLabel'))+esc(compat.worker_version||tdT('workers.versionUnknown'))+' <span class="pill '+vp[1]+'">'+esc(tdT(vp[0]))+'</span>';const vnote=(compat.verdict==='incompatible')?'<br><span class="failure">'+esc(compat.message||tdT('workers.compat.incompatibleWithHub'))+esc(tdT('workers.compat.notDispatched'))+'</span>':'';return '<article class="panel worker-card"><div class="node-head"><span class="name">'+esc(w.name||w.id)+'</span><span class="pill '+(vmap[compat.verdict]?vp[1]:'compat-ok')+'">'+esc(online?tdT('status.online'):tdT('status.offline'))+'</span></div><div class="meta">'+esc(w.platform||tdT('workers.platformUnknown'))+' · '+esc(caps)+'<br>'+esc(tdT('workers.rootsLabel'))+':'+esc(roots)+'<br>'+esc(tdT('workers.hardwareLabel'))+':'+esc(hardware)+vline+vnote+'</div></article>'}
let knownWorkers=[];
function tdJobState(s){return s==='pending'?tdT('status.queued'):s==='running'?tdT('status.processing'):s==='succeeded'?tdT('workers.state.succeeded'):s==='failed'?tdT('status.failed'):s==='skipped'?tdT('workers.state.skipped'):s}
function job(j){const stage=j.current_stage||tdT('workers.jobStageQueued');const progress=Number.isFinite(Number(j.progress))?Number(j.progress):0;const attempt=Number.isFinite(Number(j.attempt_count))?Number(j.attempt_count):0;const maxAttempts=Number.isFinite(Number(j.max_attempts))?Number(j.max_attempts):0;const options=['<option value="">'+esc(tdT('workers.assignAuto'))+'</option>'].concat(knownWorkers.map(w=>'<option value="'+esc(w.id)+'" '+((j.assigned_worker_id===w.id||j.preferred_worker_id===w.id)?'selected':'')+'>'+esc(w.name||w.id)+'</option>')).join('');const failure=j.last_error_message?'<br><span class="failure">'+esc(tdT('workers.lastFailureLabel'))+esc(j.last_error_message)+'</span>':'';const canAssign=j.job_type==='derive';return '<article class="panel job-card"><div class="job-head"><span class="name">'+esc(j.job_type)+' · '+esc(j.asset_id)+'</span><span class="pill">'+esc(tdJobState(j.state))+'</span></div><div class="meta">'+esc(stage)+' · '+Math.round(progress)+'%<div class="bar"><i style="width:'+Math.min(100,Math.max(0,progress))+'%"></i></div>'+esc(tdT('workers.attempts',{attempt:attempt,maxAttempts:maxAttempts}))+(j.lease_owner?'<br>'+esc(tdT('workers.leaseOwnerLabel'))+':'+esc(j.lease_owner):'')+failure+'</div>'+(canAssign?'<div class="assign"><select id="assignment-'+esc(j.job_id)+'">'+options+'</select><button class="btn" data-action="assign" data-mode="preferred" data-job-id="'+esc(j.job_id)+'">'+esc(tdT('workers.assignPreferred'))+'</button><button class="btn" data-action="assign" data-mode="required" data-job-id="'+esc(j.job_id)+'">'+esc(tdT('workers.assignRequired'))+'</button></div>':'')+'</article>'}
function csrfToken(){const prefix='__Host-timingdex_csrf=';const item=document.cookie.split('; ').find(function(x){return x.indexOf(prefix)===0});return item?decodeURIComponent(item.slice(prefix.length)):''}
function hubFetch(url,options={}){const headers=new Headers(options.headers||{});const csrf=csrfToken();if(csrf)headers.set('X-CSRF-Token',csrf);return fetch(url,{...options,credentials:'same-origin',headers});}
async function json(response){if(!response.ok){if(response.status===401)throw new Error('unauthorized');throw new Error(await tdApiErrorMessage(response))}return response.json()}
function statusText(msg){const el=document.getElementById('pairing');if(el&&!el.hidden)el.textContent=msg}
function showAuthCallout(){document.getElementById('auth-callout').hidden=false;document.getElementById('fleet-summary').hidden=true;document.getElementById('workers').innerHTML='<div class="empty">'+esc(tdT('workers.loginToViewWorkers'))+'</div>';document.getElementById('jobs').innerHTML='<div class="empty">'+esc(tdT('workers.loginToViewJobs'))+'</div>'}
function hideAuthCallout(){document.getElementById('auth-callout').hidden=true}
document.getElementById('login-prompt').addEventListener('click',openAdminDialog);
async function createPairing(){const b=document.getElementById('pairing-btn');b.disabled=true;const out=document.getElementById('pairing');out.hidden=false;out.textContent=tdT('workers.pairingGenerating');try{const pairing=await hubFetch('/api/v1/hub/worker-pairings',{method:'POST'}).then(json);out.innerHTML=esc(tdT('workers.oneTimePairingToken',{validity:pairing.expires_at?tdT('workers.tokenExpiresIn15'):tdT('workers.tokenSingleUse')}))+'<br>'+esc(pairing.token)+'<div class="token-actions"><button type="button" class="btn" data-copy="'+esc(pairing.token)+'">'+esc(tdT('common.copy'))+'</button><a class="btn" href="/worker-setup">'+esc(tdT('workers.goToInstallWizard'))+'</a></div>'}catch(e){out.textContent=tdT('workers.pairingError',{message:e.message})}finally{b.disabled=false}}
document.getElementById('pairing-btn').addEventListener('click',createPairing);
document.addEventListener('click',function(e){const b=e.target.closest('[data-copy]');if(!b)return;navigator.clipboard.writeText(b.dataset.copy).then(function(){b.textContent=tdT('common.copied');setTimeout(function(){b.textContent=tdT('common.copy')},1500)}).catch(function(){prompt(tdT('workers.copyPairingTokenPrompt'),b.dataset.copy)})});
async function assignJob(jobID,mode){const workerID=document.getElementById('assignment-'+jobID).value;try{await hubFetch('/api/v1/admin/worker-jobs/'+encodeURIComponent(jobID)+'/assignment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({worker_id:workerID,mode})}).then(json);load()}catch(e){alert(tdT('workers.assignError',{message:e.message}))}}
document.addEventListener('click',function(e){const b=e.target.closest('[data-action="assign"]');if(b)assignJob(b.dataset.jobId,b.dataset.mode)});
async function load(){let workers,jobs;try{const results=await Promise.all([hubFetch('/api/v1/hub/workers').then(json),hubFetch('/api/v1/jobs?limit=100').then(json)]);workers=results[0];jobs=results[1]}catch(e){if(String(e.message)==='unauthorized'){showAuthCallout()}else{document.getElementById('workers').innerHTML='<div class="empty">'+esc(tdT('workers.loadWorkersError',{message:e.message}))+'</div>';document.getElementById('jobs').innerHTML='<div class="empty">'+esc(tdT('workers.loadJobsError',{message:e.message}))+'</div>'}return}hideAuthCallout();knownWorkers=Array.isArray(workers)?workers:[];const detailed=await Promise.all((Array.isArray(jobs)?jobs:[]).map(async j=>{try{return await hubFetch('/api/v1/admin/worker-jobs/'+encodeURIComponent(j.id)).then(json)}catch(_){return j}}));const wl=Array.isArray(workers)?workers:[];const on=wl.filter(x=>x.status==='online').length,off=wl.length-on,incompat=wl.filter(x=>(x.compat||{}).verdict==='incompatible').length;const running=detailed.filter(j=>j.state==='running').length;document.getElementById('fleet-summary').innerHTML='<span class="state state--confirmed">'+esc(tdPlural('workers.fleetOnline',on))+'</span><span class="state state--attention">'+esc(tdPlural('workers.fleetOffline',off))+'</span><span class="state state--contradicted">'+esc(tdPlural('workers.fleetIncompatible',incompat))+'</span><span class="state state--draft">'+esc(tdPlural('workers.fleetRunning',running))+'</span>';document.getElementById('fleet-summary').hidden=false;document.getElementById('workers').innerHTML=wl.length?wl.map(node).join(''):'<div class="empty"><span class="label">'+esc(tdT('workers.emptyTitle'))+'</span><span>'+esc(tdT('workers.emptyWhy'))+'</span><a class="btn btn--primary" href="/worker-setup">'+esc(tdT('workers.emptyAction'))+'</a></div>';document.getElementById('jobs').innerHTML=detailed.length?detailed.map(job).join(''):'<div class="empty"><span class="label">'+esc(tdT('jobs.emptyTitle'))+'</span><span>'+esc(tdT('jobs.emptyWhy'))+'</span><a class="btn" href="/progress">'+esc(tdT('jobs.emptyAction'))+'</a></div>'}
document.getElementById('refresh').addEventListener('click',load);
window.addEventListener('timingdex:admin-auth-changed',load);
load();setInterval(load,15000);
</script></body></html>`
