package mock

import (
	"path/filepath"
	"strings"

	"github.com/evjohn-icu/nexusslate/internal/domain"
)

func Analyze(path string, m domain.MediaMetadata, hasSpeech bool) domain.StructuredAnalysis {
	name := strings.ToLower(filepath.Base(path))
	assetType := "b_roll"
	if hasSpeech {
		assetType = "talking_to_camera"
	}
	if strings.Contains(name, "screen") {
		assetType = "screen_recording"
	}
	shot := "wide"
	if m.Orientation == "portrait" {
		shot = "medium"
	}
	audio := "ambient"
	if !m.HasAudio {
		audio = "silence"
	} else if hasSpeech {
		audio = "speech"
	}
	return domain.StructuredAnalysis{
		AssetType:       assetType,
		SceneTags:       []string{m.Orientation, "local_demo"},
		Subjects:        []string{"unclassified_scene"},
		PeopleCount:     0,
		ShotSize:        shot,
		CameraMotion:    "unknown",
		Lighting:        "unknown",
		AudioType:       audio,
		HasSpeech:       hasSpeech,
		Summary:         "Local demo analysis for " + filepath.Base(path),
		UsableAs:        []string{"montage"},
		MoodTags:        []string{"unknown"},
		Quality:         "usable",
		ExtraTags:       []string{"demo"},
		EditorialReason: "Generated by deterministic local demo provider to validate the full pipeline.",
	}
}
